#+title: About
#+filetags: about
#+setupfile: ./org-templates/post.org

I am a professor of philosophy at [[https://www.okbu.edu][Oklahoma Baptist University]]. As one of only two people in the department, I teach a number of different courses. Courses that are now in my regular rotation are Introduction to Philosophy, Philosophy of Religion, Symbolic Logic, Metaphysics, Epistemology, Aesthetics, and Existentialism. I also teach the history of philosophy sequence: ancient, early modern, medieval, and American. My past research has been on the nature and justification of religious belief, the relation of religious belief to ethics, the role of mystery in religious belief, and the problem of religious tolerance. My most recent work has been on the effects of social media on community, the use of literature for moral education, and economic justice and the law of jubilee. I am currently writing an open-source book on symbolic logic. I enjoy experimenting with technology, and spend more time trying out text editors than actually writing. Currently, I use Emacs on macOS, and a number of different applications on iOS, writing in either Org mode or LaTeX. I recently retired as a chaplain in the United States Army Reserve. My service included tours at Ft. Hood, Texas, Ft. Sill, Oklahoma, a deployment to Iraq in 2007, and a deployment to Afghanistan in 2013. I'm particularly interested in the intersection of ethics, social and political philosophy, and economics. According to Matthew 6:10 — we are to pray:

#+begin_center
/"Your kingdom come. Your will be done, on earth as it is in heaven."/
#+end_center

I take this to mean that we are to not simply wait for heaven, but to work to make this world more like heaven — that is, to work to develop just, sustainable communities in which all people are valued as bearers of the divine image. 

I live in Norman, Oklahoma, with my wife, Sheri, and our Goldendoodle, Lucy. We have one daughter, Rachael, who is married to her husband, Josh. 

This site is published using Emacs and Org mode, with the template provided by [[https://opensource.com/article/20/3/blog-emacs][Sachin Patel]].

 # [[https://gohugo.io][Hugo]] and [[https://www.netlify.com][Netlify]]. The theme is [[https://github.com/WingLim/hugo-tania][Hugo Tania]], and you're welcome to view the source [[https://github.com/rlridenour/blog][here]] on Github.

