#+date: <2008-11-18>
#+title: The Monty Hall Problem
#+filetags: critical-thinking

One of the assignments in Critical Thinking was to figure the probability of winning the prize in the traditional three-door Monty Hall problem. Remember that there are three doors for you, the contestant, to choose from, but only one has the prize. The host knows what door the prize is behind, and opens another door to show you that there is nothing there. He will open neither the one you pick nor the one that has the prize. Let’s say that you pick Door 1, and Monty opens Door 2. What’s the probability that the prize is behind Door 3? From class, you know the answer is 2/3.
    
What’s important is that the host knows where the prize is. If he doesn’t know, then the probability is 1/2. You can calculate this using Bayes’ Theorem. Try it out!
    
By the way, if you can remember “1/2” then you should be able to get some extra-credit points on tomorrow’s exam. Even more points if you can do the calculation....
    


#+begin_tagline
Tagged: [[file:../tags/critical-thinking.org][Critical-Thinking]]
#+end_tagline
