#+date: <2008-05-18>
#+title: Millennium Development Goals
#+filetags: religion ethics

Yesterday, Mitch Randall, pastor of [[http://www.northhavenchurch.net/][ NorthHaven Church]] in Norman, preached on Christianity and Justice. In his message, he discussed the Millennium Development Goals, seven goals that have been adopted by the world's countries, including the United States. It is legitimate for the church to ask what we can do to help our own nation achieve its stated goals.

The eight goals are outlined on the [[http://www.un.org/millenniumgoals/index.html][ United Nations Website]]:

1. Eradicate extreme poverty and hunger\\
2. Achieve universal primary education\\
3. Promote gender equality and empower women\\
4. Reduce child mortality\\
5. Improve maternal health\\
6. Combat HIV/AIDS, marlaria and other diseases\\
7. Ensure environmental sustainability\\
8. Develop a global partnership for development

You can read a progress report [[http://www.un.org/millenniumgoals/docs/UNSD_MDG_Report_2007e.pdf][here]]. Each region of the world shows progress in almost every category, but there is still much work to do. These goals should be the goals of the church, for they certainly seem consistent with Jesus' stated mission in Luke 4:18-19: “The Spirit of the Lord is upon me, because he has anointed me to bring good news to the poor. He has sent me to proclaim release to the captives and recovery of sight to the blind, to let the oppressed go free, to proclaim the year of the Lord’s favor.”

May his mission be our own.


#+begin_tagline
Tagged: [[file:../tags/religion.org][Religion]] [[file:../tags/ethics.org][Ethics]]
#+end_tagline
