#+date: <2008-06-01>
#+title: Costa Rica
#+filetags: family


We had a wonderful week in Costa Rica. It is a beautiful country filled with charming people. We had a tour of the rain forest canopy and two bus trips through the countryside. If you ever plan a trip to Costa Rica, consider avoiding the rainy season. It did rain every day while we were there, but cleared up beautifully, of course, on the day that we left.

While we were on the bus traveling to the rain forest, our guide, Oliver, gave us a lesson on the history, geography, and culture of the country. Two things that he was particularly proud of were that the country has no army and that they have more teachers than police. Speaking of human rights in Costa Rica and the lack of class conflict, he said "We were lucky to be a poor country." I found his comment to be particularly striking. Why does this country develop into a stable and prosperous one that is free from both internal and external conflict? Oliver implies that it is because they didn't have anything that the developed world really wanted.

Things could be changing, both for us and the rest of the world, though. In this interesting piece in today's /New York Times/, [[http://www.nytimes.com/2008/06/02/opinion/l02cohen.html?th&amp;emc=th][Roger Cohen]] points out that two-thirds of last year's economic growth was in the developing world. This could indeed be a reversal of fortune.
