#+date: <2008-11-01>
#+title: Moral Relativism
#+filetags: ethics

In Ethics, Friday, I sketched out an argument against moral relativism that appeals to the standard argument /for/ moral relativism. The following is a typical argument for moral relativism:


- There is widespread disagreement about ethical claims.
- There is no rational way to settle this disagreement.
- If there is no rational way to settle a disagreement concerning a claim, then we should deny that such claims are objectively true.
- Therefore, ethical claims are not objectively true.

So, for any moral claim, that claim then there is at least one conceptual scheme in which that claim is true and at least one in which that claim is false. If this argument for moral relativism is convincing, then one should be equally convinced of this argument against moral relativism:


- There is widespread disagreement about moral relativism.
- There is no rational way to settle this disagreement.
- If there is no rational way to settle a disagreement concerning a claim, then we should deny that such claims are objectively true.
- Therefore, moral relativism is not objectively true.

Why should a claim that something is not objectively true bother someone who rejects objective truth?

Moral relativists are committed to the claim that moral truths are dependent on conceptual schemes, but if that claim is itself dependent on one’s conceptual scheme, then there is a conceptual scheme in which moral relativism is false. So, there is at least one conceptual scheme in which it is true that moral claims are true in every conceptual scheme. The only way that can be true is if moral truths are in fact true in every conceptual scheme. So, moral relativism is false.
