#+date: <2010-02-18>
#+filetags: religion
#+title: The Luxury of Cheap Melancholy

Every February, Oklahoma Baptist University celebrates Founders' Day with a special chapel service. This year's service was particularly special, commemorating the 100th anniversary of the school's founding. The service included a reenactment of W.P. Blake and G. Lee Phelps kneeling in prayer on the site in Shawnee, Oklahoma that was to become Oklahoma Baptist University.

To be honest, I can now remember only a single sentence from either prayer, but it is a sentence that I don't think I will ever forget: /"Deliver us from the luxury of cheap melancholy."/

These words may be more relevant now than they were at the time of the founding of OBU. We find ourselves struggling to recover from a recession, embroiled in two wars, worried about the future of the environment, and burdened by spiraling health care costs. Melancholy, or depression, seems to be an unavoidable response. As Phelps said, though, it is both cheap and luxurious; cheap because it costs us nothing, and luxurious because it prevents us from doing what is truly costly. Giving in to the luxury of cheap melancholy is an acceptance of the status quo, an admission that we will simply do nothing.

The alternative is to remember who we are and what God has called us to be, people of hope and grace. I was reminded of this as I witnessed a baptism at church on Sunday. In our church, before the baptismal candidate leaves the water, she places a finger in a bowl of salt and then touches the salt to her tongue. She then receives a candle, which she carries out of the baptistry. We who are witnesses are reminded that we too are called to be salt and light, to reject the luxury of cheap melancholy, and go into the world believing that we can, by the grace of God, make things better.

May it be so.


#+begin_tagline
Tagged: [[file:../tags/religion.org][Religion]]
#+end_tagline
