#+date: <2010-12-16>
#+filetags: misc quotes
#+title: Bob Feller (1918-2010)

Bob Feller, who pitched for the Cleveland Indians from 1936 to 1956, [[http://www.nytimes.com/2010/12/16/sports/baseball/16feller.html?scp=1&amp;sq=%22bob%20feller%22&amp;st=cse][died Wednesday]] in Cleveland. In Alan Schwarz's 2006 book, /Once Upon a Game: Baseball's Greatest Memories/, he spoke of his decision to leave professional baseball after the 1941 attack on Pearl Harbor and enlist in the United States Navy.

#+begin_quote
A lot of folks say that had I not missed those almost four seasons to World War II — during what was probably my physical prime — I might have had 370 or even 400 wins. But I have no regrets. None at all. I did what any American could and should do: serve his country in its time of need. The world’s time of need.

I knew then, and I know today, that winning World War II was the most important thing to happen to this country in the last 100 years. I’m just glad I was a part of it.
#+end_quote




#+begin_tagline
Tagged: [[file:../tags/misc.org][Misc]] [[file:../tags/quotes.org][Quotes]]
#+end_tagline
