#+date: <2010-04-18>
#+filetags: army
#+title: Visit to Ft. Moultrie

Yesterday, my class at the chaplain school participated in a staff ride to Charleston. "Staff ride" sounds more impressive than "field trip" but they mean the same thing. The highlight of the visit was a trip to Ft. Moultrie on Sullivan's Island. The defense of the fort in 1776 was the first major victory over the British in the Revolutionary War. Standing on the high ground at Ft. Moultrie, you can look straight across the harbor and see Ft. Sumter. The attack on Ft. Sumter on April 12, 1861 marks the beginning of armed conflict in the American Civil War. Then, if you scan to the left, you can see Morris Island, which is the site of Ft. Wagner. On July 18, 1863, the 54th Massachusetts assaulted Ft. Wagner, an event portrayed in the movie /Glory/. There, Sergeant William H. Carney secured the United States flag as the color-bearer fell, the first action for which an African-American would be awarded the Congressional Medal of Honor.

It's a moving experience to see a century of history and heroism from one spot on the South Carolina coast.


#+begin_tagline
Tagged: army
#+end_tagline
