#+date: <2010-08-16>
#+filetags: religion politics
#+title: A Mosque in NYC

I've been following the debate over the proposed Mosque near the site of the World Trade Center in New York City. Baptists have historically been champions of religious liberty, and denying Muslims the right to build a house of worship is contrary to historic Baptist principles.

The question to ask is this - would you be happy with a Christian Church at the same location? If so, then do not deny Muslim-Americans the same rights that you are willing to give Christian-Americans.

It is relevant to consider the setting for the proposed Mosque. This is not a Mosque on the grounds of a tranquil place for reflection dedicated to the memory of those who perished. Instead, this is a Mosque in a neighborhood where people live, work, and deserve to have places to worship as their conscience demands. For pictures of the neighborhood, see this post from [[//daryllang.com/blog/4421][Daryl Lang]].


#+begin_tagline
Tagged: religion politics
#+end_tagline
