#+date: <2011-11-30>
#+title: Using Keynote in Class
#+filetags: teaching

I have been using Keynote for iOS for lecture presentations in classes this semester. The process has been so easy, that this is the first semester that I have consistently used slide presentations during lectures. Most of my presentations were initially prepared on the Mac, then imported into Keynote for iOS on the iPad. Keynote for iOS seems to be fairly adept at importing transitions and effects. My only complaint is that the default font used in my preferred theme is different in the iOS version than in the desktop version of Keynote. 
    
I use the Remote app on the iPhone as a presentation controller. I was a bit apprehensive at first. I have a Bluetooth presentation controller that I preferred to use in the past. I like having the hardware buttons for moving through the slides. That way, I could simply feel the button, change the slide, and never have to look at the controller. I find that I can do the same thing with the Remote app, however. Slide changes occur when the presenter swipes a finger across the screen, exactly like navigating through screens on an iOS device. I found that it is very natural to hold the phone in one hand, and swipe the screen with the index finger of that same hand to change the slide. A swipe in the other direction moves to the previous slide. There is no need to look at the phone to change slides. It is easy, natural, and I have yet to drop the phone after a semester's worth of lectures. I can glance at the phone to see the next slide in the queue, a handy feature that my usual remote lacks.
    
When I first started using the Remote app with Keynote for iOS, the two worked seamlessly. Both the iPad and iPhone were on the same wi-fi network, so the iPhone immediately saw the presentation that was running on the iPad. At some point, though, the two stopped connecting to each other. This began at the same time that I updated devices to iOS. Unfortunately, I don't know if it is related to iOS or if it is a result of changes in the University's network. I have found that connecting the iPad to the iPhone using the personal hotspot works flawlessly. That does require a few extra steps before the presentation can begin.
    
Even so, I am extremely pleased with Keynote for iOS and the companion Remote app. I simply carry in the iPad and the adapter cable, plug it in to the projector cable, and begin the presentation. No boot-up time and not heavy laptop. It's quick, easy, and it just works, assuming you pay AT&amp;T for the privilege of using your phone as a personal hotspot.
    
