#+date: <2011-05-13>
#+filetags: religion
#+title: Calculating the End — Again and Again


Apparently, there are many discussing what to expect on May 21. Of course, it's not the first time that the end of the world has been predicted. Bill Leonard, professor of church history at Wake Forest, recently posted an article at [[http://www.abpnews.com/content/view/6387/9/][Associated Baptist Press]]  reviewing past mistaken predictions. Note the final two paragraphs:

#+begin_quote
For now, let’s keep last things last. The end will come, for individuals and ultimately for the entire enterprise, but perhaps the answers lie, not in escapist theories, but with dying whales, vanishing forests, polluted water and rising ozone, “the fire next time.” We recalculate yet another “Great Disappointment,” but refuse to listen to what the world and its non-human inhabitants are telling us. We hope for “peace and security,” plotting our escape as the planet cries in pain, edging toward its own end.

So if there is an ounce of Jesus in any of us, let’s opt out of the Rapture and stay right here to the bitter end, because there is still justice to be done and too much good to be accomplished to forsake this world, even in Jesus’ name. For Jesus’ sake let’s stay behind, loving God with all our hearts, and if we can muster it, loving our neighbors as ourselves.  What Rapture!
#+end_quote

Well said.


#+begin_tagline
Tagged: [[file:../tags/religion.org][Religion]]
#+end_tagline
