#+date: <2011-12-07>
#+title: The Rights of Women in Afghanistan
#+filetags: ethics


***  Cultural Relativism
      
For many of those that hold the position, cultural relativism is motivated by a belief that we should be tolerant of the moral beliefs of other cultures. Most of the time, this is expressed in a way that is simply inconsistent, that is, given that there are no objective, universal moral truths, we /ought/ to be tolerant of the moral beliefs of other cultures. Unfortunately, one cannot consistently assert both that there are no objective, universal, moral truths and that we have a moral obligation to be tolerant, especially since our culture is often intolerant.
    

***  Options for the Relativist
      
Even though relativists often are inconsistent, they need not be. Here are some ways that that one could try to assert a consistent relativism:
    

- When the relativist asserts that we ought to be tolerant, the assertion should not be understood as a moral claim. Instead, it should be understood as a pragmatic claim. That is, we ought to be tolerant, not because we are morally obligated to, but because it is in our best interests as a way of minimizing conflict.
- We shouldn't adopt relativism because we have a moral duty to be tolerant, of course that is inconsistent. Rather, once our culture comes to realize the truth of cultural relativism, we would naturally come to adopt an ethic of tolerance. Then, it would be true that we ought to be tolerant, since it would be part of our moral code.
- When the relativist claims that we ought to be tolerant, she means simply that tolerance is a good. There is no need to understand this as a claim that tolerance is a /moral/ good. A good is simply something that is worth pursuing, and there are several reasons why tolerance would be something worth pursuing.


***  Tolerance Only to a Point?
      
I have argued elsewhere that tolerance is not as good as one might think, since it implies an attitude of superiority toward the one being tolerated. Even so, I think it is psychologically impossible for relativists to adopt an attitude of genuine tolerance toward the moral beliefs of cultures that are radically different from our own.
    
For example, an Afghan woman reported that she was raped by her cousin's husband two years ago, and she was subsequently sentenced to twelve years in prison ([[http://www.cnn.com/2011/12/01/world/asia/afghanistan-rape-victim/index.html][see CNN's coverage]]). At first, it was reported that she would be released if she were to agree to marry her attacker, but authorities later said that the marriage was not a condition for her release. Even so, the imprisonment of a rape victim, who was then forced to care for her child in prison, is an unconscionable action according to most cultural relativists. That is, there are cultural beliefs and practices that should be changed, not simply tolerated.
    
So, what moral beliefs should be tolerated? I suspect that the level of tolerance would be highly correlated with the degree of similarity to our own moral beliefs and practices. That is, the relativist would maintain that we ought to tolerate the beliefs and practices of other cultures so long as they are not too different from our own.
    
That, however, is neither tolerance nor relativism. Instead, it is simply a thinly disguised moral realism.
    


#+begin_tagline
Tagged: [[file:../tags/org.org][Org]] [[file:../tags/ethics.org][Ethics]]
#+end_tagline
