#+date: <2015-12-22>
#+filetags: prayer religion
#+title: Prayer for the Fourth Sunday of Advent

Holy God,

When a new emperor\\
took the throne,\\
messengers were sent\\
to the rich and powerful\\
to deliver "glad tidings"\\
of Caesar, who was called\\
"savior and lord" and\\
promised to bring\\
peace to the empire\\
through the power\\
of his vast riches\\
and his mighty armies.

But when the King was born,\\
messengers from God were sent,\\
not to the rich and powerful,\\
but to those too poor\\
to be noticed by the empire.

And for the first time,\\
they heard glad tidings\\
of good news, that peace\\
would come to the world,\\
not by the power of force\\
but through the power of love.

Look within my heart, Lord,\\
this Christmas season.

May what you find there\\
reflect the humility\\
of the ones to whom\\
your messengers\\
were first sent.

And forgive me for when\\
I've turned the celebration\\
of your birth into something\\
that served the empire\\
more than it did your Kingdom.

/Amen/


#+begin_tagline
Tagged: [[file:../tags/prayer.org][Prayer]] [[file:../tags/religion.org][Religion]]
#+end_tagline
