#+date: <2015-03-15>
#+filetags: religion
#+title: The Cross-Shattered Christ, Chapter 3

Kierkegaard's /Fear and Trembling/ focuses on Abraham, an example of what Kierkegaard calls a "Knight of Faith." When I asked for other examples, someone suggested Mary, the mother of Jesus. At the time, I was skeptical, because it did not seem to me that Mary had an opportunity to reject God's plan; the angel Mary announced that Mary would conceive, and never asked Mary if she wanted to cooperate in this endeavor.

My mistake, as if often the case, is to think of Mary only as the young girl in the Christmas story, and neglect the woman that reared a child whom she surely could never keep — anguish foreshadowed by Simeon's remark by Simeon's cryptic remark to Mary, "A sword will pierce your own soul too." Mary, though, despite her anguish, has hope, as we must also. As Hauerwas states:

So may we never forget that we, the church, comprise Mary’s home. A home, moreover, that promises not safety but rather the ongoing challenge of being a people called from the nations to be God’s people. A people constituted by faith in the One who refused to triumph through the violence the world believes to be the only means possible to achieve some limited good, to insure we will be remembered. The refusal to use violence in the name of the good does not mean this people can forget those singled out in Mary’s song of triumph— that is, the poor and powerless. Rather, it means that such a people, Mary-like, must live by hope— a hope that patiently waits with Mary at the foot of her son’s cross.[fn:1]


[fn:1]: Hauerwas, Stanley (2005-01-01). /Cross-Shattered Christ: Meditations on the Seven Last Words/ (pp. 41-45). Baker Publishing Group. Kindle Edition. 
