#+filetags: critical thinking
#+date: <2015-01-20>
#+title: NRA Survey

I just received a call from the National Rifle Association today. A recorded message from the NRA Executive Vice-President concerning the U.N. Small Arms Treaty was followed by the following single question survey:

"Do you think it's OK for the U.N. to be on our soil attacking our gun rights?"

I was instructed to press "1" if I did /not/ think was OK for the U.N. to be on our soil attacking our gun rights. That was followed by a repeat instruction to press "1" if I did not think it was OK. I was then instructed to press 2 if I did think was OK for the U.N. to attack our gun rights. (Note that I was only given that instruction once.)

I am not criticizing the NRA's position on the U.N. Small Arms Treaty, primarily since I have no interest in making enemies of the most well-armed group in the country. NRA membership outnumbers the people serving the U.S. Armed Forces by over a million. Even if there are no problems with the policy position, there are several problems with the survey. First, it is obvious that the NRA is not concerned what people think about the treaty. The survey is a classic example of a push-poll. It's designed simply to push a message out to the population. This is evident from the question. What useful information do we expect to gain from asking people if they think it's OK for the U.N to attack our gun rights. Do we really not know how people will answer that question? It's no different from my polling my students to find out if they would like to get out of class early. I expect to soon hear an announcement from the NRA proclaiming that the American people are nearly unanimous in their rejection of the Small Arms Treaty. As far as information gathering goes, it's a complete waste of time and money. For propaganda pushing, on the other hand, it's very effective.

I wonder what the response rate would have been had the question been "Do you think it's OK that the U.N. negotiate a treaty designed to prevent guns from falling into the hands of terrorists?" Another group could report that the American people nearly unanimously support the Small Arms Treaty. This survey would be no better as a survey, but just as effective as a propaganda tool.

I will be curious to see what percentage of respondents the NRA reports as supporting their position. It should not be 100%, since I pressed "2" just out of spite.


#+begin_tagline
Tagged: [[file:../tags/critical-thinking.org][Critical-Thinking]]
#+end_tagline
