#+date: <2015-02-11>
#+filetags: prayer religion
#+title: Prayer for a Life that Affirms

Casie Trotter sent me a link to a wonderful passage from Nietzsche's 1882 book, /The Gay Science/. This is aphorism 276, his resolution for that year:

#+begin_quote
I want to learn more and more how to see what is necessary in things as what is beautiful in them — thus I will be one of those who make things beautiful... I do not want to wage war against ugliness. I do not want to accuse; I do not even want to accuse the accusers... And all in all and on the whole: some day I want only to be a Yes-sayer!
#+end_quote

I'm not sure what Nietzsche would think of his work prompting this week's prayer, but here it is anyway:

God of beauty and wonder,

Let me be known\\
not for what I found ugly,\\
but for what I found beautiful.

Not for what was harmed,\\
but for what was healed.

Not for what I tore down,\\
but for what I built up.

Not for what I despised,\\
but for all that I loved.

In the name of the one\\
who sees the beauty in us all,

/Amen/
