#+date: <2015-01-20>
#+filetags: religion
#+title: Who Is My Enemy?

The parable of the Good Samaritan is prompted by a lawyer's question in Luke 10:29, "But wanting to justify himself, he asked Jesus, 'And who is my neighbor?'"   That phrase, "But wanting to justify himself" plays an important role in a sermon of mine, where I claimed that this places the lawyer on par with the typical caller on a talk-radio show. On this reading, the phrase means something like, "In order to impress those listening in," or "In order to sound smarter than he really was." 

I'm no longer confident, though, that I've been fair to the lawyer. Why would any 1st-century Jew have asked what the greatest commandment was? Everyone would have agreed that it is found in Deuteronomy 6:5, "You shall love the Lord your God with all your heart, and with all your soul, and with all your might." 

And given the themes in the prophets and the law, Jesus' claim that the second greatest commandment was the requirement to love one's neighbor as oneself  in Leviticus 19:18 would also strike listeners as obvious. 

So, the lawyer, having just asked a question to which everyone listening would have though the answer was obvious, then proceeded to ask another question with an even more obvious answer, "Who is my neighbor?"  Maybe the lawyer suspected that God's commandment was more radical than we ever assumed. 

Maybe the lawyer was present four chapters earlier, when Jesus uttered these words, "But I say to you that listen, Love your enemies, do good to those who hate you, bless those who curse you, pray for those who abuse you."

I've been thinking about this for the past few days after hearing Mitch Randall's sermon at [[http://northhavenchurch.net][NorthHaven Church]] on loving our enemies. What would Jesus have said if the same lawyer were to have asked, "Who is my enemy?"

Sixteen months in a combat zone taught me that identifying enemies can be difficult. It is not in the enemy's best interests to be identifiable as an enemy. It may also be that I am the one who is antagonistic, but self-deceptive about the extent and nature of my antagonism. Even if I have them, it may be difficult for me to see myself as a person who makes enemies.

So, how do I begin to understand who my enemy is? Maybe I should begin by answering these questions:

- In whose failure would I take pleasure?
- At whose expense do I direct my humor?
- To whom do I need to feel superior?

Sometimes we feel like we are surrounded by enemies. I fear that they are enemies that we have constructed for our own sake. 

Lord have mercy.
