#+date: <2015-01-13>
#+filetags: misc
#+title: New Friends

We met some very interesting people during our stay at the [[http://www.ullikana.com][Ullikana Inn]] in Bar Harbor, Maine. There were two couples there that, generally with some other couples, return every year. Before dinner, everyone met for some refreshments, during which they told about their usual evening activity at the inn. Evidently, the first time that the couples had been at the inn together, they found themselves in that room making the sort of small talk that people do when they don't really know each other. Then, one asked, "What should we talk about?" Another answered, "How about what happens to you when you die."

After telling us this, one turned to me and said, "You bring the topic this evening. The only rule is that it has to be controversial." Given that the Slender Man violence had been in the news, I asked if artists and writers had moral obligations that should govern how and what kinds of art are made available to the public. It was a very lively conversation that lasted more than two hours. Friends from different backgrounds, all discussing a controversial topic, with no one taking offense---it was a wonderful time.


#+begin_tagline
Tagged: [[file:../tags/misc.org][Misc]]
#+end_tagline
