#+date: <2015-03-07>
#+filetags: religion
#+title: The Cross-Shattered Christ, Chapter 2

I struggled with the second chapter of Hauerwas' book, /The Cross-Shattered Christ/[fn:1], not because the chapter was particularly hard to follow, but because it forced me to reflect on my life as a teacher and minister. The chapter opened with a discussion of the reticence of the Gospels, why do they not tell us everything that we want to know? Why is Jesus simply silent on what many of us think are the most important questions of the day? We tend to be uncomfortable during times of silence, so we attempt to fill in the gaps, even when we have little of value to say. In much the same way, we are often uncomfortable with uncertainty, that is, being faced with questions for which we have no clear answers, so we take on the role of spokespeople for Christ. 

Hauerwas points out the presumptuousness of this: "Our attempt to speak confidently of God in the face of modern skepticism, a skepticism we suspect also grips our lives as Christians, betrays a certainty inappropriate for a people who worship a crucified God."

One thing that I love about my job is the significant conversations that I have with colleagues and students. At lunch yesterday, I felt the discomfort of having no answer when asked about how to respond to particularly difficult questions asked by sincere followers of other religions.

It's not that I have nothing to say, it's rather that what I have to say seems insufficient for the task at hand. All of my clear and concise explanations suddenly seem incomplete and inadequate in the shadow the Cross of the Crucified One.

[fn:1] Hauerwas, Stanley (2005-01-01). /Cross-Shattered Christ: Meditations on the Seven Last Words/ (p. 18). Baker Publishing Group. Kindle Edition.
