#+date: <2015-01-13>
#+filetags: prayer
#+title: Christ the King Sunday

Mitch opened his sermon at NorthHaven on Christ the King Sunday recounting the scene at the end of The Return of the King in which Aragorn, the newly crowned king, bows down to the hobbits. That brought to mind their first meeting in The Fellowship of the Ring where Frodo is trying to decide if Aragorn should be trusted:

#+begin_quote
At last Frodo spoke with hesitation. "I believed that you were a friend before the letter came," he said, "or at least I wished to. You have frightened me several times tonight, but never in the way the servants of the Enemy would, or so I imagine. I think one of his spies would - well, seem fairer and feel fouler, if you understand."
#+end_quote

What does a king look like?

Is he haughty,\\
unapproachable,\\
controlling,\\
and cold?

Regal and magnificent,\\
to be respected and admired,\\
but only from afar?

Majestic and powerful,\\
a conquering hero\\
who rides into the city\\
astride a warhorse?

Surely the king\\
would not appear\\
as the son of\\
a poor family,\\
a laborer with\\
calloused hands?

Homeless,\\
who owns nothing,\\
and rides into the city\\
on a shabby, borrowed donkey?

One who suffered injustice,\\
and was executed by\\
the forces of the state?

Father,

Teach me to\\
embrace the King\\
as he is,\\
and not the King\\
as I want him to be.

/Amen/


#+begin_tagline
Tagged: prayer
#+end_tagline
