#+date: <2015-01-13>
#+filetags: prayer
#+title: The Sixteenth Sunday After Pentecost

As I was driving to work this morning, the person behind me honked as I was waiting for a pedestrian to cross the street at a marked crosswalk. I was still fuming and telling myself that I wish I could have told them what I really thought as they pulled into the parking space beside me. Fortunately, I had just heard Mitch Randall's sermon on Daniel in the lions' den the day before. With that said, here is the prayer for the week:

Lord,

It seems like I'm always in the lions' den.

I tell myself that I'm Daniel,\\
a man of faith who was slandered by the envious,\\
the righteous one who was unjustly attacked by his enemies.

I can fool myself, Lord,\\
but surely I'm not fooling you.

Most of the time,\\
I'm one of the lions.\\
Ready at any time to open my mouth\\
to tear down,\\
to hurt,\\
to wound,\\
to destroy.

And when I lack the ability to shut my own mouth,\\
please shut it for me,\\
until it's filled with words\\
that proclaim\\
justice,\\
healing,\\
mercy,\\
and love.

Then, loosen my lips,\\
so that the stream of mercy and love\\
can flow from you, through me,\\
and transform the lions' den\\
into a sanctuary of your grace.

/Amen/




#+begin_tagline
Tagged: [[file:../tags/prayer.org][Prayer]]
#+end_tagline
