#+date: <2015-05-21>
#+filetags: education
#+title: In Praise of an Unsafe Education

I was excited to see an excerpt from Neil Gaiman's new book recently in [[http://www.usatoday.com/story/life/books/2014/10/23/neil-gaiman-trigger-warning-cover-excerpt/17719799/
][/USA Today/]], explaining why he chose "Trigger Warning" as the title. It didn't strike me that the title could be controversial until I saw this [[https://twitter.com/skinnygrlsfloat/status/561365292693999617][tweet]] asking why he chose such a "thoughtless and insensitive title."
  It's no surprise that such accusations prompted a rather thoughtful and sensitive response from Gaiman, one of my favorite authors.

** Trigger Warnings

A trigger warning is a statement that a film or work of literature portrays  scenes that some may find disturbing, especially for those who have experienced similar events themselves. Like Gaiman, I have conflicted feelings about trigger warnings.

On one hand, we ought to be sensitive to the emotional needs of others. Several years ago, I was at a conference with an Army colleague who had lost friends in the Korangal Valley of Afghanistan. When the speaker began showing clips from the documentary /Restrepo/, I watched my colleague appear increasingly uncomfortable.  From her reaction, I don't think she was prepared to relive those experiences, especially in public.

On the other hand, it seems that many of the trigger warnings used today in higher education, or at least Christian higher education, are not used to protect those who have had disturbing experiences in the past. Instead, they are used to protect innocent minds from having particular kinds of experiences at all, like hearing vulgar speech or seeing a nude body. Such trigger warnings are concessions to those who want education to be safe, and students to be protected from the vulgar, profane, and offensive.

** Safe Christian Education?

The world, though, is often vulgar, profane, and offensive, and to portray it otherwise is a lie. It is impossible for students to receive a Christian education and never encounter the world as it, for a Christian education in which students never encounter accounts of violence, drunkenness, and rape would be a Christian education in which students never read Genesis — that is, it would not be a Christian education at all.

Trigger warnings serve two purposes. First, they give students the opportunity to opt out of engaging the material. Second, they give students the opportunity to mentally and emotionally prepare themselves for the disturbing material that lay ahead. To do the former is to opt out of an education, but what could be wrong with the latter?

There are some events to which the only appropriate emotional responses are shock and horror. To portray these events in ways that do not elicit shock and horror is to do so in a way that ensures that students fail to have the appropriate moral responses. So, in an effort to avoid emotional harm to students, we have caused moral harm instead. Our goal in Christian education should not be to sanitize the world, but to encounter it as it is in the context of a community of love and grace.

As God's creation, the world is filled with examples of beauty and grace, but in its present fallen state, it is also filled with examples of cruelty and horror. To portray only the horror is to leave students in cynicism and despair; to portray only the beauty is to leave students in gullible idealism and naiveté. Neither genuinely prepares students to deliver the gospel of Christ to a beautiful, yet broken, world.

