#+date: <2015-01-20>
#+filetags: prayer
#+title: Christmas Prayer

This was a prayer I delivered at NorthHaven Church in Norman for the Christmas Day service on December 25, 2011.\\

Gracious Father,

We gather here in this place to celebrate the day the world changed.\\
On that day, one who was pure spirit became incarnate;\\
The eternal Word became clothed in a frail human body;\\
That which no human had ever touched was laid by a gentle mother's hand into a simple manger;\\
The eternal and timeless now had a beginning;\\
The infinite became finite;\\
On that day, God became human.

While still in the garden, we began to build a wall;\\
A wall that separated ourselves from you;\\
A wall which we built, but could never tear down.\\

You tore down the wall when you brought your firstborn into the world,\\
and said to that babe in the manger,\\

"You are my son; this day I have begotten you."

You have spoken to us in many ways, through the prophets, through the beauty of nature, and through the voice of conscience.

On that first Christmas day, though, you spoke has you had never spoken before.

Lord, here we are,\\
Help us to listen,\\
Help us to hear.

/Amen/


#+begin_tagline
Tagged: [[file:../tags/prayer.org][Prayer]]
#+end_tagline
