#+date: <2015-01-13>
#+filetags: religion political
#+title: Thoughts on Burwell vs. Hobby Lobby

Social media was certainly inundated with  reactions to yesterday's Supreme Court ruling in /Burwell vs. Hobby Lobby/. The majority were at the two extremes --- either this was a great victory for religious liberty and a stunning blow to the Obama administration, or it was an unprecedented power-grab by religious conservatives and wealthy corporate America that will only prevent women from getting the health care that they need.

As is generally the case, neither extreme position is correct. The /Affordable Care Act/ is safe, and only certain corporations will be exempt from providing health coverage in very limited instances, provided that the government can easily provide such coverage. So, I don't think that the situation is as bad as some progressives have concluded.

That's not to say that I think that the situation is good. I fear that the Supreme Court has placed the government in the position of having to determine what counts as a sincerely held religious belief, which may have more far-reaching implications for religious liberty than simply having to provide comprehensive health coverage.

In any case, this is just one of the problems with linking health-coverage and employment. The solution to this and other problems, including the exorbitantly high cost of health care in the United States compared to other countries, is to adopt a single-payer system. 


