#+date: <2015-04-15>
#+filetags: prayer religion philosophy
#+title: Dostoevsky, Suffering, and the Prayer for the Week

This past weekend  was a weekend of funerals — two very different people, both with lives that had been cut tragically short. Then, on Tuesday, I learned of two more tragedies involving families in the Army units that I serve. Coincidentally, all of this happens as one of my classes is studying one of the central works on the problem of suffering, the chapter titled in "Rebellion" in Dostoevsky's masterpiece, /The Brothers Karamazov/.[fn:1] In the novel, Ivan argued that moral decency and the love of humanity demand that we should refuse to live in what he thought to be a clearly unjust world. The only decent thing to do would be to, in his words, "return one's ticket."

Ivan makes two related mistakes here. First, he believes that he can judge the world from an objective position. This, though, ignores the fact that we are embedded and entangled, part of the world that we presume to judge. The second mistake is assuming that the world that we now experience is morally static, that is, assuming that the suffering of the innocent has always, and will always, occur, and if God created this world, he created it to be an unjust world.

As I said, these mistakes are related. I am not an innocent, objective judge. The level of justice or injustice in the world is, in an important way, partly a function of my action or inaction. The world that we experience, then, is one of our own creation; not one that we have created ex nihilo, but rather through our perversion of God's good creation. God, though, can redeem even that which we have corrupted. So, instead of maintaining, like Ivan, that we cannot accept this world of God's, we should instead strive, by God's grace, to make his world into that which he always planned for it to be, and promised that it would in fact someday be. We do this, not by loving humanity, but by loving our neighbors, wherever and whoever they may be.

Father,

Grant us the faith to be\\
your redeemed people,\\
who announce to the world\\
by word and deed\\
the miracle of your\\
reconciling love.

/Amen/

[fn:1] My favorite novel, in case there is still anyone who knows me that doesn't realize it.


#+begin_tagline
Tagged: prayer religion philosophy
#+end_tagline
