#+date: <2015-05-10>
#+filetags: prayer religion
#+title: Prayer for Mothers Day

Mother's Day can be an awkward time in the life of the church. There is a great deal of internal pressure to commemorate the day, but we should acknowledge that there are many who are understandably uncomfortable on this day. There are those who may have painful memories of abuse at the hand of their biological mothers, others who may have never known their mothers, and many others who have never had, nor will ever have, children of their own. So, in this week's prayer, I've tried to celebrate, not motherhood per se, but the nature of caregivers, whoever they may be.

Loving God,

We give thanks this day,\\
for those who care\\
for children,\\
for aging parents,\\
and for neighbors,\\
for anyone who needs\\
a warm smile,\\
a cheerful greeting,\\
or a kind word.


And we are blessed\\
by those who\\
love every child\\
as one of their own,\\
for reflected\\
in their eyes,\\
we see the face\\
of Jesus.

/Amen/

