#+date: <2015-01-19>
#+filetags: metaphysics quotes
#+title: Permanent Impermanence


#+begin_quote
As I wrote recently, everything in existence is permanently impermanent. 
#+end_quote

#+ATTR_HTML: :class source
[[http://minimalmac.com/post/14973202531/the-only-standard-is-impermanence Minimal Mac][Patrick Rhone]]

I detect shades of Heraclitus here.

Question: is this a paradox? Answer: probably not, unless Rhone is committed to the belief that nothing at all, even impermanence, is permanent. It is a good opportunity to do some analytic philosophy, though. 

What is permanence? Is it a real property, or is it a derivative analyzed in terms of the real properties of an object? What's the status of self-predication; must permanence itself be permanent? If there is nothing in existence that is permanent, then does that mean that abstract objects (numbers, sets, etc.) do not exist? Does that commit us to something like subsistence for abstract entities? Does permanence mean simply that an object always exists, or does it also mean that an object never changes? If the first, then most, if not all, theists would reject the claim that nothing in existence is permanent. If the second, then we would have to at least reject the doctrine of the immutability of God.

Here's my first attempt to symbolize permanence, attempting to say that that an object is permanent just in case for any property that the object has any time, it has that property at all times.



\[ \forall x \{\textrm{Px} \leftrightarrow [\forall \textrm{F} \forall t_{1} (\textrm{F}xt_{1} \rightarrow \forall t_{2} \textrm{F}xt_{2})]\} \]


This is why people hate analytic philosophers.



#+begin_tagline
Tagged: [[file:../tags/philosophy.org][Philosophy]] [[file:../tags/quotes.org][Quotes]]
#+end_tagline
