#+date: <2015-01-13>
#+filetags: prayer
#+title: The Ninth Sunday After Pentecost

When we discuss the concept of rights in political philosophy, I confess that I feel conflicted. On one hand, the recognition of, and commitment to, the rights of others is essential to treating them with the dignity that is due to one created in the image of God. On the other hand, the constant practice of demanding my own rights does not seem consistent with the claim to follow the one that Paul described in Philippians 2:


#+begin_quote
Let the same mind be in you that was in Christ Jesus,\\
who, though he was in the form of God,\\
did not regard equality with God\\
as something to be exploited,\\
but emptied himself,\\
taking the form of a slave,\\
being born in human likeness.\\
And being found in human form,\\
he humbled himself\\
and became obedient to the point of death—\\
even death on a cross.
#+end_quote

Philippians 2:6-8 (NRSV)

So, yesterday's sermon on entitlement by Mitch Randall at [NorthHaven Church](http://northhavenchurch.net ) was particularly convicting. Here is the prayer that it prompted:

/The petty heart/\\
/feels entitled to everything,/\\
/and finds grace in nothing./\\

/Blessed is the one/\\
/who feels entitled to nothing,/\\
/but finds grace in everything./

/Amen/






#+begin_tagline
Tagged: prayer
#+end_tagline
