#+date: <2015-06-17>
#+filetags: philosophy religion
#+title: Evil and Perception

[[http://www.etgarkeret.com][Etgar Keret's]] new book, [[http://www.amazon.com/Seven-Good-Years-Memoir-ebook/dp/B00OYXWKDY/ref=sr_1_1?s=books&ie=UTF8&qid=1434540345&sr=1-1&keywords=the+seven+good+years][/The Seven Good Years/]] is a collection of essays concerning the interval between the birth of his son and the death of his father. I was particularly intrigued by this statement from the story on [[http://www.npr.org/2015/06/16/414896816/what-etgar-keret-learned-from-his-father-about-storytelling-and-survival?utm_source=facebook.com&utm_medium=social&utm_campaign=npr&utm_term=nprnews&utm_content=20150616][NPR]]:

#+begin_quote
I'm pretty good at feeling sorry for myself, [but] ... the fact that he survived the Holocaust always kind of seemed to him that something good had happened to him in life. And life since the Holocaust always seemed to surprise him for the better, and there was no bitterness in him. He said, "You know what? I've been smoking two packs a day since I was 14 years old for more than 65 years and if after that you get a cancer, it's a fair deal," he says. "It's fair. I've got nothing to complain [about] and I've lived a full life, I want to live as much as I can, but when I die when I die, I won't go out kicking and screaming."
#+end_quote

Could it be that the force of the problem of evil is a matter of one's attitude? What is the difference between people who focus on their suffering and those who focus on their overcoming that suffering?


#+begin_tagline
Tagged: philosophy religion
#+end_tagline
