#+date: <2015-01-13>
#+filetags: religion
#+title: Charge to the Church

/For the NorthHaven Church Deacon Ordination Service/\\
/April 27, 2014/

I have been asked to deliver a charge to the congregation on this occasion. A reasonable question to ask is why should the church be tasked with anything in the event of a deacon ordination? It is the new deacons that have been tasked to do something; the church is simply the recipient of those actions, isn't it? So, what is the point of a charge to the church?

Every charge to the church that I've heard has contained two important components, the charge to pray for deacons and their families and to support them in their ministry. Prayer is important to mention, but I won't dwell on it, for I know that you have already begun to pray for these new deacons, just as you have been praying for our deacons ever since we established NorthHaven's deacon ministry.

Instead, I'd like to focus on the second aspect of the charge, the charge to support the deacons in their ministry. How, besides prayer, do we support those who minister, especially when they are ministering to us?

There are two crucial ways, both exemplified by events in the life of Jesus. In John chapter 12, Mary, the sister of Martha and Lazarus, anointed Jesus' feet with a pound of costly perfume. When one of the disciples objected, Jesus defended her action. Jesus allowed Mary to minister to him. Too often, though, we are like Peter, who, when Jesus knelt before him to wash his feet, initially refused Jesus the opportunity to minister. We refuse ministry for many reasons, sometimes pride, sometimes a sense of unworthiness, but often, I suspect, because of a feeling of self-sufficiency.

The most important way to support those who minister is to allow them to be what God has called them to be. Despite our pride, none of us are ever really self-sufficient. If we were honest, we would have to confess that we are all, at different times, broken people in need of ministry. When we refuse ministry from one who has been called by God to serve, we, like Peter, refuse ministry from the Lord himself.

So, we best support our deacons by allowing them to minister to our needs, but we must also lovingly help them understand those needs. In Mark 10, as Jesus was leaving Jericho on his final journey to Jerusalem, a blind man called out "Son of David, have mercy on me." Jesus commanded the disciples to bring the man to him, then asked him directly, "What do you want me to do for you?" The man was neither too afraid, nor too embarrassed, to reply. James was speaking of other things when he said this, but his advice applies to ministry as well — you have not because you ask not. I have always been grateful for those who gently taught me how I should pray for them, and showed me the ways I could encourage them. Their guidance turned my fumbling attempts at ministry into something that we both needed.

We tend to think of ministry as something that one person does for another, in other words, we think that there is one that actively gives and another that passively receives.  True ministry, though, depends as much on the one who receives as the one who provides. True ministry occurs when broken people together find healing in a community through which flows love, grace, hope, and faith. When we empower people to become what God has called them to be, a miracle happens, the Lord himself comes to us, walks among us, touches and heals us. May we, by God's grace, be a community in which he is welcome. Let this be the charge. Will you accept?

