#+date: <2015-05-08>
#+filetags: prayer religion
#+title: Unexpected Grace

This week's prayer is simple, but informed by events of the week that profoundly impacted me. First, NorthHaven Church​ was in the area that sustained some wind damage in Wednesday night's storm. The next day, Imam Imad Enchassi​ of the Islamic Society of Greater Oklahoma City graciously asked if we needed any help. To all our Muslim friends, /As-Salaam-Alaikum/.

Second, I see in my students a level of spiritual depth that I certainly did not have in my 20's and may not yet have in my 50's — one that moves beyond the superficial trivialities that pass for spirituality in much of American religion, but instead shows a deep understanding of the message of Jesus.

Gracious and Loving God,

Thank you for those moments\\
when grace breaks in\\
to interrupt our lives\\
in surprising ways,\\
and unexpected voices\\
teach us once again\\
what it means\\
to follow Jesus.

/Amen/


#+begin_tagline
Tagged: prayer religion
#+end_tagline
