#+date: <2015-01-13>
#+filetags: prayer
#+title: Love and Attention

A few days ago, Casie Trotter sent me this quote from George Saunders: "I think that art is a form of paying attention and, for me, attention is love." This is an important point, although I would phrase it differently. Attention is not love, because attention can easily be followed by an act of hate. Attention is a necessary condition of love; it is impossible to love something unless on pays attention to the object of love. In the same way, it is impossible to hate something without also being willing to pay attention to it. Without attention, there is neither love nor hate, there is just indifference—the great sin of the Laodicean church.

Traditionally, the theme of the second Sunday of Advent is love. Darley and Batson's famous Good Samaritan study[fn:1] shows that a major impediment to paying attention is simply being in a hurry. Ironically, then, the many activities and rushed pace of the Advent season make it harder for us to pay attention, and therefore less likely that Advent will be a season of love.

Let us begin to love by paying attention.

Holy Spirit,

Forgive me, for\\
although I can see,\\
I am too often blind.

Instead of obstacles in my path,\\
let me see opportunities\\
to slow down,\\
to linger,\\
to pay attention,\\
to love.

For time is never wasted\\
when it is spent in love.

/Amen/


[fn:1] /Journal of Personality and Social Psychology/, vol. 27, no. 1, 100-108.


#+begin_tagline
Tagged: prayer
#+end_tagline
