#+date: <2015-07-12>
#+filetags: religion quotes
#+title: Strength Enough?

Mike Bumgarner quoted part of this passage in a sermon this morning. It is worth reflecting on:

#+begin_quote
This is where a tremendous decision takes place: whether we Christians have enough strength to witness before the world that we are not dreamers with our heads in the clouds... that our faith really is not opium that keeps us content within an unjust world. Instead, and precisely because our minds are set on things above, we are that much more stubborn and purposeful in protesting here on earth... Does it have to be that Christianity, which began as immensely revolutionary, now has to remain conservative for all time? That every new movement has to blaze its path without the church, and that the church always takes twenty years to see what has actually happened? If it really must be so, then we must not be surprised when, for our church as well, times come when the blood of martyrs will be demanded. But this blood if we truly have the courage and honour and loyalty to shed it, will not be so innocent and shining as that of the first witnesses. Our blood will be overlaid with our own great guilt.
#+end_quote

#+ATTR_HTML: :class source
Dietrich Bonhoeffer, /DBW/, Vol. 11, 446.
