#+date: <2015-01-13>
#+filetags: ethics politics religion
#+title: A Parents Love

Saturday afternoon, protestors lined the bridge at Rogers Avenue and Interstate 44 in Lawton, Oklahoma. They held signs demanding that the children currently detained for illegal immigration be sent back to their home countries.

[[http://www.npr.org/2014/07/17/332251674/as-immigration-crisis-grows-a-protest-movement-gains-steam][National Public Radio]] recently reported on another protest:

#+begin_quote
This week outside the southern Arizona town of Oracle, Marla and Bruce Bemis — along with several dozen of their neighbors — were lined up along a road waving American flags and holding signs, as patriotic music occasionally played in the background. Word had come that the federal government was planning to bring some of the detainees to a local academy for troubled youth.

"You know it's a shame that they're kids, if they're kids, but I guess their parents didn't care that much to send them on that journey to here," says Marla Bemis.
#+end_quote

This brought to mind the story of Moses:

#+begin_quote
A man from the family of Levi married a Levite woman. The woman became pregnant and had a son. She saw there was something special about him and hid him. She hid him for three months. When she couldn't hide him any longer she got a little basket–boat made of papyrus, waterproofed it with tar and pitch, and placed the child in it. Then she set it afloat in the reeds at the edge of the Nile. (Exodus 2:1-3)
#+end_quote



How much love must it take to send one's child into the unknown? These are parents who care very much indeed.


God of love,\\
\\
Jesus took a little child\\
into his arms, and said,\\
"Whoever welcomes a child\\
in my name, welcomes me."\\
\\
There are days\\
when the Kingdom seems so near,\\
but others when it seems so far.\\
\\
Today, as the death toll rises\\
in the land where\\
the Prince of Peace once walked,\\
help me to honor your words\\
with more than just my lips.\\

/Amen/
