#+date: <2015-02-24>
#+filetags: religion
#+title: The Cross Shattered Christ, Chapter 1


Reflections on /Cross-Shattered Christ: Meditations on the Seven Last Words/ by Stanley Hauerwas, Chapter 1.



This chapter is perfect reading for the week following Ash Wednesday. The traditional liturgical declaration uttered by the minister "Remember that you are dust, and to dust you shall return" is a reminder of our mortality. Ash Wednesday is quickly forgotten, though, just as the somber reflection that occurs after a funeral quickly fades as life returns to normal. As Hauerwas points out, this death, the death of the Son of God, is like no other. To truly come terms with the death of Jesus is to understand that life can never return to normal. Jesus' plea from the cross, "Father, forgive them; for they do not know what they are doing," challenges our understanding both of God and of ourselves. In Hauerwas' words, "We are made members of a kingdom governed by a politics of forgiveness and redemption. The world is offered an alternative unimaginable by our sin-determined fantasies."[fn:1] We are offered a glimpse of this kingdom in the lives of a few who are able to live in the shadow of the cross. May we find the strength to dwell there during this season of Lent.

 
[fn:1] Hauerwas, Stanley (2005-01-01). *Cross-Shattered Christ: Meditations on the Seven Last Words* (p. 18). Baker Publishing Group. Kindle Edition.


#+begin_tagline
Tagged: [[file:../tags/religion.org][Religion]]
#+end_tagline
