#+date: <2015-01-20>
#+filetags: religion
#+title: Ordination Charge for Brian Warfield

I was honored to be asked to deliver the following charge to the minister at the ordination of Brian Warfield, one of our best former students. It was a pleasure to see Brian, Misty, and to meet their children. It was also great to catch up with friends at Spring Creek Baptist Church, where Brian was ordained. The text of my remarks follows:

Charge to the Minister\\
Ordination of Brian Warfield\\
April 11, 2012





Brian, I am honored to have this opportunity to participate in your ordination service. I have often wondered where students have ended up, and to what kind of ministry they were led. Facebook has changed that. Now I generally know even more than I wanted. Sometimes, I'm surprised to hear that a former student is now on a church staff, or that someone else is not pastoring somewhere. Sometimes, the proper response is not surprise, but sadness, especially when gifted young ministers feel compelled to leave their own tradition because there is no place there for them to serve. In this case, though, I felt a deep sense of pleasure when I read that one of my best students was being ordained by one of my favorite churches.

You have asked me to deliver the charge to the minister. A charge is a kind of challenge that is laid before you, something for you to keep in mind as you walk this path on which God has led you. So, I now charge you to remember these three things.

First, remember that the questions are quite often more important than the answers. Too many sermons are answers to questions that no one is asking. As such, they are vain, empty, and useless. One of the most common causes of failed ministries occurs when a minister is called to a new church, and begins proclaiming answers before asking enough of the right questions. Answers that come too quickly tend to show a lack of respect for the question, which is taken to be a lack of respect for the questioner.

Jesus understood the importance of questions. When he was asked, "Who is my neighbor?" he replied, after a story, with another question, "Which one of these was the neighbor?" Understanding comes not when we are force-fed answers, but rather when we are equipped to answer our own questions. Before that, though, we need to learn how to ask the right questions. That is one of the most valuable things that a minister can do for a congregation.

Finally, there are some questions for which there are no sufficient answers. Jesus' cry from the cross is one of those, "My God, my God, why have you forsaken me?" When in the presence of such suffering, the right response is not to provide answers, but, with fear and trembling, recognize that the ground upon which you are standing is holy ground.

The second thing I'd like you to remember is that Kingdom growth is not the same thing as church growth. I remember having a conversation with someone when we were starting NorthHaven, our church in Norman. He asked me a question that I wasn't quite sure how to answer - "What is your market?" At first, I laughed and replied “Liberals.” The more I think about the question, the more it disturbs me. If we treat the church as a marketplace, we shouldn’t be surprised that people are engaging in comparison shopping. We have failed to make disciples, instead we are making customers. And in the back of my mind, I hear Jesus’ words in the temple: “You shall not make my Father’s house a house of trade.”

The heart of the problem is that we have made church growth the ultimate goal. And when we do so, the church tends to become something that God never intended.  Sometimes I wonder just how much of what we do in church today has anything to do with being the church described in the New Testament. In Acts 2, we get a glimpse of the church as it’s described in the New Testament. Daily activities include taking care of each other, sharing meals, and praising God. Everything, interestingly enough, except for evangelism as we now understand it. Yet, the Scripture says that the Lord daily added to their number.

Church growth is wonderful, but it shouldn't be the goal. To make it the goal is to run the risk of compromising the Gospel. The easiest way to achieve church growth is by preaching what Bonhoeffer called "cheap grace."  When tempted, think back to chapter  6 of John's Gospel. After Jesus proclaimed a difficult teaching, John said that many of his disciples left him. It is a poignant scene when Jesus turned the twelve, and asked "Do you also wish to go away?" Making church growth the criterion of a successful ministry is to adopt a model of ministry that would make Jesus' ministry on earth a failure.

The goal of church growth is going to church. The goal of kingdom growth is /being/ the church, a community of love, the place where the kingdom of God has come into the world.

Finally, keep this in mind - remembering where you came from is more important than knowing where you're going. Although we're confident in our ultimate destination, none of us knows what intermediate stops we will have along the way.

Why are we here? Why is ordination important? Not so that you can minister. If you had not already shown that you were ministering to those around you, this church would have never considered ordination. We are not a sacramental tradition, so we do not believe that any special grace will flow to you today. So, why do we ordain you? My friend and colleague, Kevin Hall, likes to quote Spurgeon as saying ordination is the laying of empty hands on an empty head. I've read some of your academic work, so I'm confident that it is not an empty head that we lay hands on today. Still, though, why is this important?

Paul's letters to Timothy give us a clue. 1 Timothy is primarily instructional. It's about taking care of the business of the church. Things are good, let's get down to work. 2 Timothy, though, has a different tone. After the salutation, Paul writes:

#+begin_quote
Recalling your tears, I long to see you so that I may be filled with joy. I am reminded of your sincere faith, a faith that lived first in your grandmother Lois and your mother Eunice and now, I am sure, lives in you. For this reason I remind you to rekindle the gift of God that is within you through the laying on of my hands; for God did not give us a spirit of cowardice, but rather a spirit of power and of love and of self- discipline.
#+end_quote

What events prompted this change of tone? Why does Paul think it necessary to remind Timothy of the faith of his family and of the time of his ordination? I suspect that it's because Timothy is experiencing one of those times in ministry that we all have. There will come a time when this thought comes to mind. It has happened to me, and I'm sure that it has happened to many others. The thought is this: "The only mistake that God ever made in history is calling me to ministry." When that thought comes, remember this day.

You need to be ordained for the same reason that Jesus needed to hear the voice of the Father at his baptism, saying "This is my beloved Son, in whom I am well pleased." The memory of that moment may have been exactly what Jesus needed when it came time to face the trials that lay ahead. Ordination is important for those times that you don't think that you are up to the task, when you don't feel that you have the right skills or the right words. When that time comes that you cannot seem to believe in yourself, remember that today, a church, the Body of Christ, believed in you. That my friend, is surely enough.

Amen
