#+date: <2015-01-13>
#+filetags: prayer religion
#+title: The Third Sunday After Pentecost

God of grace,

We live in a word of concrete barricades, wooden fences, and stone walls that we have built to protect, separate, control, and hide; some hastily thrown up in hours, others carefully built in weeks or months.

Other walls, though, are constructed over a lifetime, and are just as real and just as effective—downcast eyes, hostile stares, and stony silence—walls constructed to prevent the pain of rejection, or to keep others out of our comfortable lives.[fn:1]


![Beyond the Wall](https://www.flickr.com/photos/79286287@N00/215951891/)

Yet we dream of a place where the barricades can be taken down, a place without fear, hunger, want, or need; a place with neither revenge nor retribution, for there are no wrongs to made right; a world filled with peace, justice, love, and grace—not another world, but this world, transformed and redeemed.

How can we build such a world when we only know how to build walls?

Lord have mercy on us.

/Amen/

[fn:1]: "Beyond the Wall" by Giuseppe Bognanni, released on Flickr under the Creative Commons Attribution License.
