#+date: <2016-11-10>
#+filetags: prayer religion
#+title: After the Election — Love

There are circumstances during which my failure becomes clearly evident, and the events of the past few days have given me needed opportunity to reflect on that failure.

God's commandment is to love — a commandment given not to an abstract entity such as government or the church, but a commandment given to me.

Even more, God commanded me to love my neighbor — not the world or humanity, but my neighbor, the one who weeps in fear and pain, the one who offends me, the one with whom I disagree, and the one of whom I take no notice.

May God have mercy on me, a sinner.

God who sustains us,

If we are to rejoice together,\\
may we taste the strength\\
of your justice and peace.\\

If we are to suffer together,\\
may we drink deeply\\
from your sacred tears.\\

If we are to live together,\\
may we feast on your love,\\
knowing that there is one rule\\
at the table of the Lord:

"Little children, love one another."

/Amen/


#+begin_tagline
Tagged: [[file:../tags/prayer.org][Prayer]] [[file:../tags/religion.org][Religion]]
#+end_tagline
