#+date: <2016-07-31>
#+filetags: religion ethics
#+title: Should the Church Bear the Welfare Burden?

I should have rather asked if the church /alone/ should bear the burden of providing welfare. There is no doubt that the church, myself included, should bear more of the burden of caring for the poor, for that is just one of the many sacrificial things Jesus calls us to do. The church, though, cannot bear the welfare burden as it is today. Ron Sider, in /Just Generosity: A New Vision for Overcoming Poverty in America/, estimates that shouldering just the cost of Medicaid would cost each Christian congregation approximately one-half million dollars per year. Note that this includes /each/ congregation, including exceptionally large churches that may well be able to afford the cost, but the median size of a Christian congregation in America is now 75 regular participants.[fn:1] So, a family of four in the median-sized congregation would have to shoulder a burden of nearly 27,000 dollars, simply to provide the services now provided by Medicaid. One can only guess at the cost of providing the full level of social services now provided by the government.

This does not mean that the church should not be developing creative ways of caring for those that Jesus and the prophets called "the least of these." It does mean, though, that the church taking on more of a burden[fn:2] does not relieve the state, nor the rest of the country, from sharing that burden. In Psalm 72, a prayer for guidance for the king, Scripture describes God's hope for the one who leads the state: "May he defend the cause of the poor of the people, give deliverance to the needy, and crush the oppressor." To allow the state to shirk its responsibility for caring the poor means that the state will no longer fulfill its God-given role of crushing the oppressor, but instead allows the state to become the oppressor — surely not something to which a government of the people should aspire.

[fn:1] [[http://hirr.hartsem.edu/research/fastfacts/fast_facts.html#sizecong][Hartford Institute for Religion Research]]

[fn:2] "Burden" is not the right word to use here. Caring for one another should be a joy. That we see it as a burden is a sin for which we will have to repent.


#+begin_tagline
Tagged: religion ethics
#+end_tagline
