#+date: <2016-12-13>
#+filetags: prayer religion
#+title: The Offensive Jesus

The Gospel text for the third Sunday of Advent in year A is Matthew 11:2-11, which, on the surface, seems like an odd choice for the Christmas season, especially for a day known as the "Sunday of joy." It opens with what is apparently some doubt on the part of John the Baptist: "When John heard in prison what the Messiah was doing, he sent word by his disciples and said to him, 'Are you the one who is to come, or are we to wait for another?'"

The third chapter of Matthew records John speaking of the wrath to come and the unquenchable fire that will be used to burn the chaff. It appears that the messiah that John got did not look much like the messiah that John expected.\\

Too often, our celebration of Christmas shows that we, like John, also would prefer another messiah. To paraphrase Ricky Bobby in Talladega Nights, we like the Christmas Jesus best – the sweet, calm, beautiful, inoffensive, unchallenging, non-threatening Jesus of the carol "Silent Night." This Jesus doesn't call us to follow him, for he never leaves the manger, and certainly doesn't go to the cross. We are like John Updike's title character in /Rabbit, Run/, who "...has no taste for the dark, tangled, visceral aspect of Christianity, the going through quality of it, the passage into death and suffering that redeems and inverts these things."

The babe born in Bethlehem, though, would soon become the one who offended religious sensibilities and challenged the power structures of the day. In his own words, he came to preach good news to the poor and to liberate the oppressed. He was perceived by the Romans to be such a political threat that he was executed on a cross. It could very well be the case that the only person in Matthew's birth narrative to truly understand the implications of the event was Herod.

We feel happy at the manger, but joy is found on the road beyond — even if that road leads to the cross. So, as we search for meaning this Christmas season, may we look beyond the birth narratives to consider the Christ-hymn of Philippians 2; that this Jesus

#+begin_quote
...who, though he was in the form of God,\\
did not regard equality with God\\
as something to be exploited,\\
but emptied himself,\\
taking the form of a slave,\\
being born in human likeness.\\
And being found in human form,\\
he humbled himself\\
and became obedient to the point of death —\\
even death on a cross.\\
#+end_quote



Prayer:

May I come to Christmas this year\\
seeking not the image I have created,\\
but the Christ begotten of the Father,\\
recognizing that the manger of Bethlehem\\
was but the first stop on the journey to the cross.

/Amen/


#+begin_tagline
Tagged: prayer religion
#+end_tagline
