#+date: <2016-11-23>
#+filetags: religion
#+title: On Christian Unity

Comedian Emo Phillips is credited with writing this classic – voted in a recent contest as the best religious joke of all time.

#+begin_quote
Once I saw this guy on a bridge about to jump. I said, "Don't do it!" He said, "Nobody loves me." I said, "God loves you. Do you believe in God?"

He said, "Yes." I said, "Are you a Christian or a Jew?" He said, "A Christian." I said, "Me, too! Protestant or Catholic?" He said, "Protestant." I said, "Me, too! What denomination?" He said, "Baptist." I said, "Me, too! Northern Baptist or Southern Baptist?" He said, "Northern Baptist." I said, "Me, too! Northern Conservative Baptist or Northern Liberal Baptist?"

He said, "Northern Conservative Baptist." I said, "Me, too! Northern Conservative Baptist Great Lakes Region, or Northern Conservative Baptist Eastern Region?" He said, "Northern Conservative Baptist Great Lakes Region." I said, "Me, too!"

Northern Conservative Baptist Great Lakes Region Council of 1879, or Northern Conservative Baptist Great Lakes Region Council of 1912?" He said, "Northern Conservative Baptist Great Lakes Region Council of 1912." I said, "Die, heretic!" And I pushed him over.
#+end_quote

It’s a funny joke, and like most good jokes, it captures something true, in this case disturbingly true, about our history as Christians. Today, according to /Oxford’s World Christian Encyclopedia/, there are over 33,000 Christian denominations in the world. This is partly a sign of healthy diversity, but it's also a sign of some deeply unhealthy divisions.

The first three verses of Ephesians 4[fn:1] contain this beautiful plea for Christian unity:

Therefore, as a prisoner for the Lord, I encourage you to live as people worthy of the call you received from God. Conduct yourselves with all humility, gentleness, and patience. Accept each other with love, and make an effort to preserve the unity of the Spirit with the peace that ties you together. (Eph. 4:1-3)

Eight verses later, Paul speaks of another kind of unity that Paul calls unity of faith:

He gave some apostles, some prophets, some evangelists, and some pastors and teachers. His purpose was to equip God’s people for the work of serving and building up the body of Christ until we all reach the unity of faith and knowledge of God’s Son. (Eph. 4:11-13a)

The unity of the Spirit is something that we are to work towards now, while unity of faith and knowledge appears to be eschatological — something that we will have in the end. We continue to exclude more and more people from our various groups, acting as if cooperation and fellowship require doctrinal unity. Paul's charge to preserve the unity of Spirit assumes disagreement, otherwise there is no need to urge patience.[fn:2]

When we exclude, we show pride, impatience, and hardness of spirit, not the humility, gentleness, and patience of Paul's mandate. In the end, we sacrifice the thing that Paul urges us to protect, for the sake of something that we cannot yet have. We either demonstrate intolerance, or, at best, show tolerance from a distance. Neither is the love that Christ commanded.


# You are one body and one spirit, just as God also called you in one hope. There is one Lord, one faith, one baptism, and one God and Father of all, who is over all, through all, and in all.


[fn:1] All Scripture references are from the /Common English Bible/.

[fn:2] This is a point made by Larry Hurtado in [[https://homebrewedchristianity.com/2016/11/04/destroyer-of-the-gods-larry-hurtado-talks-early-church-distinctiveness/][[https://homebrewedchristianity.com][this episode]] of Tripp Fuller's excellent podcast, /Homebrewed Christianity/.

