#+date: <2016-12-28>
#+filetags: prayer religion
#+title: Walls

In light of the recent political discussion concerning building walls, here is a devotional that I wrote in 2009 when the church assisted on a Habitat for Humanity project.

I'm usually in favor of building walls, but not when it just becomes another way to burn bridges.

** Prayer

Almighty God, 

I give thanks for those who are here today to help build this house, for those who have already worked to bring us to this point, and for those who will be here in the future. May you watch over all that happens here, filling us all with the joy of doing your work.

We pray also that your blessings will fill this house and those who will live here. May the sounds of laughter echo from these walls, and may love fill these rooms.

/Amen/

** Devotional

Even though the ones that we see here are far from finished, we should never underestimate the importance of building walls. Nehemiah left the court of the Persian king to rebuild the walls of Jerusalem. For the people of Jerusalem, walls represented safety, security, and an opportunity to be the people of God free from oppression by the enemies that surrounded them.

Not all walls are good, though. I'm speaking of the walls that we build that separate communities, that keep us apart, those invisible walls that we erect to protect our own comfort zones. In some ways, these are the walls that we cherish the most, but it is these walls that God wants torn down. As Paul says in 1 Corinthians 1:10, "Now I appeal to you, brothers and sisters,​ by the name of our Lord Jesus Christ, that all of you be in agreement and that there be no divisions among you, but that you be united in the same mind and the same purpose."

We come here from different backgrounds, different families, and different churches. This is an opportunity to build some very important walls, but also maybe to tear down a few walls. May what we do here express that great truth of the Gospel expressed in Galatians 3:28, "There is no longer Jew or Greek, there is no longer slave or free, there is no longer male and female; for all of you are one in Christ Jesus."

So go now, building those walls that need to go up, and tearing down those walls that need to come down. 

In the name of Jesus, 

/Amen/


#+begin_tagline
Tagged: prayer religion
#+end_tagline
