#+date: <2016-11-08>
#+filetags: politics
#+title: Interesting Times

There are three statements that have become known as the "Chinese" curses, although I should point out that there is no record of any Chinese equivalents. They are three things to wish upon one's enemies. Three things that, on the surface, seem like things that a person should surely want; but appearances, as we all know, are often deceiving.

The first, and the mildest: "May you live in interesting times." 

There are worse things, however, than simply living in interesting times. It is far worse to be at the center of those interesting events. Hence, the more severe curse: "May you come to the attention of powerful people." 

There are times, though, when even that is not enough. For those times, you need the most severe curse, something devilishly cruel and viciously twisted: "May you find what you are looking for."

Early this morning, Donald Trump delivered his acceptance speech after winning the 2016 United States presidential election. 

These are interesting times indeed.

