#+date: <2016-07-09>
#+filetags: prayer religion
#+title: Prayer for the Nation

Eternal God, you whose image lies in the hearts of all people,\\
Hear our prayer, as we pray for our nation.

Help us to remember that you love all with your great love,\\
that all faith is an attempt to respond to you,\\
and that the desires of other hearts are known by you,\\
just as our desires are known.
\\
Lead us to use what you have given us\\
for freedom, justice, and equality;\\
Not only for our own sake,\\
but for those to whom these things have been denied.

In our pride, teach us humility;\\
In our strength, teach us grace;\\
In our callousness, teach us compassion;\\
In our riches, teach us generosity,\\
In our ignorance, give us wisdom;\\
In our fear, give us courage;\\
In our anxiety, give us peace.

May we be a source of love in the midst of hatred,\\
And an instrument of peace in the midst of conflict.\\
We pray these things in the name of the most high,\\
The source of all that is good, holy, and true.

/Amen/
