#+date: <2016-08-07>
#+filetags: prayer religion
#+title: A Wedding Prayer and Blessing

I officiated a wedding for a former student and dear friend yesterday. Here is the prayer and blessing from the ceremony:

God of grace, hear our prayer,

We give thanks for this day, for we need it desperately.\\
The world inundates us with messages of\\
helplessness and hopelessness, emptiness and despair,\\
until we are tempted to feel that all is lost.\\

Then we come to this place,\\
and we find that there is still hope,\\
for the love that spoke the world into being\\
has drawn these two people together,\\
so that they may create their own world,\\
a life together,\\
marked by beauty,\\
dedicated to peace,\\
and surrounded by love.

Protect, guide, and bless them in their marriage.\\
Surround us all with your love, now and always.

Now, may the slanting rays of the sun[fn:1]\\
light the path before you,\\
as the love of God surrounds you,\\
to guide you on this journey together.\\
May God guard your hearts\\
from anything that might separate you,\\
and shelter you in his love, forever.

/Amen/

[fn:1]: For those who haven't taken my existentialism course, "the slanting rays of the sun" is a metaphorical image that Dostoevsky uses in /The Brothers Karamazov/.
