#+date: <2016-12-21>
#+filetags: religion
#+title: Christmas Communion Liturgy

Peace be with you,

When a new emperor took the throne in Rome, messengers were sent to the rich and powerful to deliver "glad tidings" of Caesar, who was called "savior and lord" and promised to bring peace to the empire through the power of his vast riches and his mighty armies.

But when the King was born in Bethlehem, messengers from God were sent, not to the rich and powerful, but to those too poor to be noticed by the empire.

And for the first time, they heard glad tidings of good news, that peace would come to the world, not by the power of force, but by the power of love, not through a conquering army, but through the crucified Christ.

The messiah had come, but the city of Bethlehem was unprepared. There was no welcome; there was no room. His birth was largely ignored by the powerful, and noticed only by some shepherds and a few foreigners.

We, like Bethlehem, were also unprepared, but thanks be to God that even in our uncertainty, Christ called to us; even in our hesitation, Christ came to us; even in our sin, Christ died for us.

Christmas reminds us that ready or not, God has come into the world, and we are not alone. By sharing communion together we recognize and remember God's presence and proclaim the great mystery of the faith:\\

Christ has died,\\
Christ has risen,\\
and Christ will come again.

We stand before the table, surrounded by God's people, who will soon partake together — powerful symbols of God's presence and his grace.

God before you,\\
God around you,\\
God within you.

Come to his table.

/Taking of the bread./

Christ's body was broken not just to make a statement, and not merely for the sake of some cause.

Christ's body was broken for you, and for me.

Eat, and remember.

/Taking of the cup./

Just as his body was broken, his blood was shed, and God died, so that we may live.

Drink, and give thanks.

/Amen/



#+begin_tagline
Tagged: religion
#+end_tagline
