#+date: <2016-06-23>
#+filetags: emacs
#+title: Emacs on the iPad

The iPad Pro has more people considering using the iPad for production, not just for entertainment. I have long been jealous of those who could use an iPad for most of their work, especially now, as iPad displays get bigger and nicer. I would love to be able to throw an iPad and keyboard into a small bag and be able to use the same tool for both reading and writing.

Unfortunately, though, two things have kept me from being able to easily do that. First, I do almost of all my work in Emacs, and I'm afraid that Apple would never allow Emacs on the iPad. Second, except for blog posts, almost everything I write eventually becomes a LaTeX document that is compiled into a PDF.

I'm sure that most people wouldn't be troubled at all by either of these problems. My projects usually begin as Markdown files, and there are some decent Markdown editors on iOS. Most of these are limited to using one subfolder in Dropbox, and I have a folder for each course, writing project, my website, etc. A larger problem is that Emacs becomes a finely tuned, personal tool for a user. With one keystroke, I can renumber ordered lists, insert a reference from my bibliography database, commit changes to a git repository, and many other things. Once this has become ingrained, it is very difficult to go to anything else. I can write LaTeX on the iPad, but I can't compile. That still has to be done on another machine. So, while others are carrying their nice, light tablets, I've been schlepping a MacBook Pro.

A few days ago, I noticed that [[http://www.digitalocean.com][Digital Ocean]] has a remote server plan with 20 GB of solid state storage for five dollars a month. It only has 512 MB of memory, but that seems to be plenty for Emacs and Vim. I signed up, started a machine, and installed Ubuntu. I installed Emacs, Vim, Pandoc, and LaTeX. I changed the shell to the fish shell, and moved all of my configuration files. Since the configuration files are all on Github, moving them to the machine was simple.

So, the good news is that I'm now writing this in Emacs on the iPad. The bad news is, since I had given up being able to use the iPad to write, I traded in my larger iPad for an iPad mini. Now, I really will be looking longingly at those iPad Pros I see at Starbucks.


#+begin_tagline
Tagged: [[file:../tags/emacs.org][Emacs]]
#+end_tagline
