#+date: <2016-06-01>
#+filetags: ethics
#+title: Reconciliation and Hope

I wrote this eight years ago, after President Obama's election:

#+begin_quote
The year that I was born, 1963, was marked by these significant events:

- In April, Martin Luther King was arrested and jailed in Birmingham.
- In May, “Bull” Connor, the Commissioner of Public Safety in Birmingham used police dogs and fire hoses on a demonstration in Birmingham.
- In June, Medgar Evers, the NAACP Field Secretary for Mississippi, was murdered outside his home.
- In August, Martin Luther King delivered his famous “I Have a Dream” speech at the Lincoln Memorial in Washington, D.C.
- In September, four young girls were killed in the bombing of the Sixteenth Street Baptist Church in Birmingham.

Tuesday, an African-American man was elected President of the United States.

The country has certainly come far. European countries are generally viewed as far more progressive than the United States, but, as far as I can tell, no European country is even remotely close to being able to select a member of a minority racial group as head of government.

That said, we still have a long ways to go before we can claim to have achieved racial reconciliation. On November 5, David Garland, President of Baylor University, issued a statement concerning recent incidents of racial conflict on Baylor’s campus. We cannot hope to achieve reconciliation in this country if we are not even able to achieve it in the Church. It is time for the Church to not only ask forgiveness for our past sins regarding slavery, but to recognize that failing to take action to create a better future is itself a sin.

If nothing else, this week’s election is a sign of hope.
#+end_quote

The events of the past eight years proved that progress requires more than simply hope.
