#+title: Prayer for the Fourth Sunday of Advent
#+date: <2017-12-24>
#+filetags: prayer religion

A prayer for Mitch Randall’s last Sunday as pastor of NorthHaven Church, before he takes his new position as executive director of the Baptist Center for Ethics.

God of peace and joy,

For centuries,\\
Israel anticipated\\
the coming of the Messiah;\\
and as one expectation\\
was fulfilled,\\
another was born,\\
for we still long\\
for the day when\\
that same Messiah\\
will come again.

Christmas is still a day\\
when old dreams are fulfilled,\\
and new dreams are born.

We give thanks for what\\
this church has become\\
in the years that Mitch\\
has been with us:

For those who have\\
been rejected,\\
it is a place to feel welcome.

For those who have\\
felt constrained,\\
a place to be free.

For those whose gifts\\
have been denied,\\
a place to serve.

And so it is fitting\\
that at Christmas\\
We share with the world.\\
this gift that we have received,

And may we, through our\\
words, actions, and gifts,\\
declare to the world\\
that there is still\\
good news of glad tidings,\\
for all people, everywhere.

/Amen/



#+begin_tagline
Tagged: prayer religion
#+end_tagline
