#+title: Thoughts on Trump and the Johnson Amendment
#+date: <2017-05-04>
#+filetags: religion politics

Some thoughts on President Trump's Executive Order on "Promoting  Free Speech and Religious Liberty" that was recently issued:

First of all, the President's executive order doesn't change anything about religious leaders engaging in political action from the pulpit.  This is from section 2, the relevant part of the order:

>The Secretary of the Treasury shall ensure, to the extent permitted by law, that the Department of the Treasury does not take any adverse action against any individual, house of worship, or other religious organization on the basis that such individual or organization speaks or has spoken about moral or political issues from a religious perspective, where speech of similar character has, consistent with law, not ordinarily been treated as participation or intervention in a political campaign on behalf of (or in opposition to) a candidate for public office by the Department of the Treasury.

All it says is that speech that has so far been considered consistent with the law should continue to be considered consistent with the law. Nothing changes, so foes of the Johnson Amendment should be severely disappointed. It is, like much of what seems to be coming from Washington these days, Shakespearean: "full of sound and fury, signifying nothing."

Given recent discussions, it appears that the current law is severely misunderstood by many. Most political activity by churches is, and has always been, completely legal. Churches and leaders have always been allowed to speak on issues, legislation, and most matters of political concern. What pastors are not allowed to do is to campaign, in their role as pastors, for candidates. That is, they are to refrain from partisan campaigning in exchange for the tax-exempt status of their churches.

Regardless of Johnson's motivation for desiring this (which, knowing Johnson, was likely not altogether virtuous), it is a good thing. Granting tax-exempt status is subsidizing religious activity – churches, synagogues, and even mosques get services from the city for which they pay nothing, services like police and fire protection. For these free services, only one accommodation is required, that is to refrain from campaigning for candidates. 

The law in no way restricts the free speech rights of anyone. Churches are always welcome to give up their tax-exempt status. Churches should just not expect citizens to pay for their campaigning by means of that tax-exempt status. If the current law is changed, then note that citizens will be subsidizing, through the taxes which pay for police, fire departments, etc., the political campaigns of candidates that they do not support.
