#+date: <2017-06-26>
#+filetags: religion
#+title: Making Beautiful Things

Yesterday's worship at [[http://www.northhavenchurch.net][NorthHaven Church]] was planned and led by Autumn Lockett, Josh Lockett, and Chris Canary. I was particularly struck by the words of one of the songs: "You make beautiful things out of the dust... You make beautiful things out of us."

Those words were exemplified later when the members of the congregation gathered to each put fingerprint leaves on Josh Lockett's sketch of a tree, fingerprints from the young and the old, from those who have been in the community for years, and from those who have been there for only months. Each contributed to the beauty of the painting, just as each has contributed to the beauty that is the NorthHaven community, diverse individuals connected by branches of relationship to a common trunk that is NorthHaven Church. When I widen my perspective, though, I see that what looks like a trunk is just another branch --- one that is connected to other branches through Jesus Christ, and together we form the tree that is the Church, holy and catholic.

May God continue to make beautiful things out of all of us.

/Amen/




#+begin_tagline
Tagged: religion
#+end_tagline
