#+title: Ethics of War Handout
#+date: <2017-11-30>
#+filetags: ethics political

These are some concepts and terms used in a presentation on the ethics of war, given at Oklahoma Baptist University on December 1, 2017.

** Pacifism

- Consequentialist Pacifism: :: Although war is not intrinsically wrong, the benefits of war are always outweighed by the costs.
- Deontological Pacifism: :: War is always intrinsically wrong, regardless of its consequences.

** Doctrine of Double Effect

War could be permissible, even if we know that innocent lives will be lost, if

1. Taking innocent life is not the reason that we go to war,
2. The lives that are saved are proportionally greater than the lives that will be lost,
3. Taking innocent life is not the means to saving lives, and
4. Saving lives is otherwise permissible.

** Just War

- Jus ad bellum: ::  Conditions that determine when a state can justly go to war.
- Jus in bello: :: Conditions that specify how a war must be fought
- Jus post bellum: :: Conditions that determine when one can justly end hostilities.

*** Jus ad bellum

- Just cause
- Right intention
- Proper authority/declaration
- Last resort
- Probability of success
- Proportionality

*** Jus in bello

- Obey international law
- Discrimination
- Proportionality
- Humane treatment of POW’s
- No means /mala in se/

*** Jus post bellum

- Just cause
- Right intention
- Discrimination
- Proportionality
- No reprisals



** Just Peacemaking

Ten principles of just peacemaking:[fn:1]

1. Support nonviolent direct action.
2. Take independent initiatives to reduce threat.
3. Use cooperative conflict resolution.
4. Acknowledge responsibility for conflict and injustice and seek repentance and forgiveness.
5. Advance democracy, human rights, and religious liberty.
6. Foster just and sustainable economic development.
7. Work with emerging cooperative forces in the international system.
8. Strengthen the United Nations and international efforts for cooperation and human rights.
9. Reduce offensive weapons and weapons trade.
10. Encourage grassroots peacemaking groups and voluntary associations.

* Footnotes

[fn:1] From /Just Peacemaking: Ten Practices for Abolishing War/, 2d ed., edited by Glen Stassen (Pilgrim Press, 2004).


#+begin_tagline
Tagged: [[file:../tags/ethics.org][Ethics]] [[file:../tags/politics.org][Politics]]
#+end_tagline
