#+date: <2017-01-13>
#+filetags: quotes philosophy
#+title: Nietzsche on Military Buildup


#+begin_quote
And perhaps the great day will come when a people, distinguished by wars and victories and by the highest development of a military order and intelligence, and accustomed to make the heaviest sacrifices for these things, will exclaim of its own free will, "We break the sword," and will smash its entire military establishment down to its lowest foundations. Rendering oneself unarmed when one has been the best-armed, out of a height of feeling—that is the means to real peace, which must always rest on a peace of mind; whereas the so-called armed peace, as it now exists in all countries, is the absence of peace of mind. One trusts neither oneself nor one's neighbor and, half from hatred, half from fear, does not lay down arms. Rather perish than hate and fear, and twice rather perish than make oneself hated and feared—this must some day become the highest maxim for every single commonwealth, too.
#+end_quote

--- Friedrich Nietzsche, /The Wanderer and His Shadow/, 284.
