#+date: <2017-06-03>
#+filetags: prayer religion
#+title: Pentecost Prayer

A prayer for tomorrow's sermon at Spring Creek Baptist Church:

God of life,

Sometimes our prayers are as parched as the desert\\
and our hearts as dry as the dunes of sand.

We take offense at things that don't matter,\\
but ignore the ones that do.

When others are hungry,\\
we are full.

When others are hurting,\\
we are numb.

When others are cold,\\
we rest comfortably\\
beneath warm blankets of apathy.

But even in our self-righteousness,\\
we still feel something,\\
a deep ache of longing,\\
a thirst for something\\
greater than ourselves,\\
a lingering thought\\
that you are still there.\\

Emmanuel,\\
God with us.\\

Despite our weakness,\\
you have called us to be your people,\\
ambassadors of your kingdom.

On this Pentecost Sunday,
lead us once more to the well of your grace,\\
bathe us again in the streams of your mercy.

Open the floodgates of your love,\\
and let the rivers flow.

/Amen/


#+begin_tagline
Tagged: [[file:../tags/prayer.org][Prayer]] [[file:../tags/religion.org][Religion]]
#+end_tagline
