#+date: <2017-04-13>
#+filetags: religion
#+title: Thoughts on Maundy Thursday

This day of the church calendar, Maundy Thursday, gets its name from John 13:34, which, in the Latin Vulgate, begins with "mandatum novum" — a new commandment. After washing the feet of the disciples earlier in chapter 13, Jesus told them,

#+begin_quote
I give you a new commandment, that you love one another. Just as I have loved you, you also should love one another. By this everyone will know that you are my disciples, if you have love for one another.
#+end_quote

A commandment to love, though, should strike us as odd, because we generally think of love as a feeling or emotion. It makes no sense to command a feeling or emotion, however, for those are not within our immediate control. We can only be commanded to act. So, unless Jesus' command is simply pointless, love must be a way of acting, or living as Jesus lived; in his words, "For I have set you an example, that you also should do as I have done to you." (John 13:15)

I have good reason to continue to think of love as just an emotion. By thinking of love as a feeling, I avoid having to keep the commandment to love. So, I have taken something that I simply do not want to do, and turned it into something that is impossible for me to do. As long as I pretend it is impossible, I can deny that there is any obligation to keep the commandment. That way, I can go on loving only those whom I like, and thus continue to rest comfortably in my own self-righteousness.

May God forgive me.

