#+title: Ordination Prayer
#+date: <2017-12-09>
#+filetags: prayer religion

/This is a prayer for an ordination service at NorthHaven Church on December 9, 2017/

God of grace and hope,

We confess that, sometimes,\\
we are like Israel in Egypt,\\
overwhelmed by life and\\
tempted to believe that\\
you have abandoned your people.

In this, though, we have hope,\\
though Israel had forgotten you,\\
you did not abandon her.\\
Instead, you called Moses\\
to be her minister.

And so, from the desert\\
of our dry and parched lives,\\
you continue to call —\\
not from a burning bush,\\
but from within,\\
from a heart aflame\\
with passion for\\
the kingdom of God\\
and for your people.

Today, we give thanks for Kim,\\
a minister with such a heart,\\
who, like Moses,\\
has answered your call.

Grant her the vision\\
to see things as they are,\\
and the spiritual imagination\\
to recognize what they could be.

May her laughter be joyful;\\
her anger, righteous;\\
her compassion, gentle;\\
her witness, bold;\\
and her love, deep.

Fill her with the\\
power of the Almighty,\\
who took what was\\
formless and void\\
and created the universe,\\
then declared it good.

May her ministry\\
be the means by which\\
you continue to take\\
what is broken and empty,\\
and create that which is\\
new, beautiful and good.

In the name of the Father\\
who gives us our mission,\\
and of the Son,\\
whose obedience is our model,\\
and of the Spirit,\\
who gives us strength\\
for our task.

Three persons,\\
one God,\\
forever and ever.

/Amen/



#+begin_tagline
Tagged: prayer religion
#+end_tagline
