#+title: A New School Year
#+filetags: prayer religion
#+date: <2017-08-17>

As this year's chairperson of the Faculty Council, I am privileged to open our first employee meeting with a reading from Scripture and a prayer. This year, our academic year begins one week after the horrific display of racism and violence in Charlottesville, Virginia. That event prompted my reflection on the following text.

** Colossians 3:1-15

#+begin_quote
So if you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God. Set your minds on things that are above, not on things that are on earth, for you have died, and your life is hidden with Christ in God. When Christ who is your life is revealed, then you also will be revealed with him in glory.

Put to death, therefore, whatever in you is earthly: fornication, impurity, passion, evil desire, and greed (which is idolatry). On account of these the wrath of God is coming on those who are disobedient. These are the ways you also once followed, when you were living that life. But now you must get rid of all such things—anger, wrath, malice, slander, and abusive language from your mouth. Do not lie to one another, seeing that you have stripped off the old self with its practices and have clothed yourselves with the new self, which is being renewed in knowledge according to the image of its creator. In that renewal there is no longer Greek and Jew, circumcised and uncircumcised, barbarian, Scythian, slave and free; but Christ is all and in all!

As God’s chosen ones, holy and beloved, clothe yourselves with compassion, kindness, humility, meekness, and patience. Bear with one another and, if anyone has a complaint against another, forgive each other; just as the Lord has forgiven you, so you also must forgive. Above all, clothe yourselves with love, which binds everything together in perfect harmony. And let the peace of Christ rule in your hearts, to which indeed you were called in the one body. And be thankful.
#+end_quote

** Prayer

God of hope and Lord of life,

Thank you for this time\\
to gather together\\
as friends and colleagues\\
to kindle the excitement\\
and hope of a new beginning.

We give thanks and pray for our students,\\
for they come here with hopes and dreams,\\
and believe that this is the place where\\
those hopes and dreams can become reality.

May they never leave thinking\\
that their dreams were too big,\\
but instead go from here\\
with a new vision of their role\\
in the redemptive story\\
that is far greater than\\
even they had ever dared to dream.

We pray for ourselves,\\
that you would protect us from the temptations\\
to answer too quickly,\\
to respond with cynicism,\\
and to serve the spirit that crushes hope,\\
instead of our God who makes all things possible.

We pray for our nation,\\
still reeling in shock\\
from what we have seen this week.

The temptation is to despair,\\
asking who are we,\\
and what can we do\\
when anger, wrath, and malice\\
appear to win the day?

But we are those who have been raised with Christ,\\
and of all people we should have hope,\\
for we have been to the cross,\\
and we have seen what love can do.

May our lives bear witness to that love\\
and to the resurrection power\\
that the darkness, as hard as it may try,\\
can never overcome.

In the name\\
of the Father,\\
and of the Son,\\
and of the Holy Spirit.

Three persons,
One God,\\
forever and ever.

/Amen/



#+begin_tagline
Tagged: [[file:../tags/prayer.org][Prayer]] [[file:../tags/religion.org][Religion]]
#+end_tagline
