#+date: <2017-03-14>
#+filetags: religion politics
#+title: Usury in Oklahoma

Yesterday, the House of Representatives of the State of Oklahoma passed [[http://www.oklegislature.gov/BillInfo.aspx?Bill=Hb1913&Session=1700][HB 1913]], a bill giving lenders the ability to charge an Annual Percentage Rate of 205.92% on a $1,500 loan.[fn:1]

This bill is inconsistent with historical Christian values and should be opposed by conservatives and progressives alike. The practice of taking interest on loans is expressly forbidden in several passages of Scripture:

- Exodus 22:25-27
- Leviticus 25:35-38
- Deuteronomy 23:19-20; 24:6
- Psalm 15:5
- Ezekiel 18:7-8; 22:12
- Nehemiah 5:6-13[fn:2]

Before 1500, every Christian writer who discussed the practice expressly condemned the practice of charging interest. Ambrose called it wicked, and Augustine, in the /Enarration on Psalm 129/ said that the person who loaned at interest would "...go into the flame." Like the church fathers, every church council that discussed loaning at interest condemned it. Luther also condemned charging interest, although Calvin did not. Calvin saw interest as a necessity in a fallen world, since the lender is risking non-payment. Interestingly, though, in his /Commentary on the First Twenty Chapters of Ezekiel/, he said "It is always wrong to exact usury from a poor man." For Calvin, it looks like interest can be charged, just not to the poor. One could also appeal to the Founding Fathers. The colonies set an interest cap of 8%. After 1776, most states limited interest at 6%.

Note that the Bible and the Church for the first 1600 years of its existence defined usury simply as charging interest on a loan. We now define it as charging excessive interest, which shows a compromise to the modern world. Regardless, taking a stand against this bill is taking a stand for traditional Christian values; something the right should certainly support.

[fn:1] The full text of the bill in its various versions can be found [[http://www.oklegislature.gov/BillInfo.aspx?Bill=Hb1913&Session=1700][here]]. It was sponsored by [[https://www.facebook.com/pg/Chris-Kannady-for-House-91-1406719546213093/about/?ref=page_internal][Rep. Chris Kannady]]. It is surprising that a veteran should sponsor a bill like this, given that young soldiers are often targets for predatory lenders. The bill passed [[http://www.okhouse.gov/56LEG/OKH00208.TXT][59-31]]. Note that the bill allows a 17% monthly rate, equivalent to a 206% annual rate.

[fn:2] Strictly speaking, these passages forbid taking interest from fellow Israelites. Christians should be willing to expand this, given Jesus' expansion of our understanding of neighbor.


