#+date: <2017-03-16>
#+filetags: politics economics
#+title: Obama's Economic Record

In a recent discussion, one participant claimed that the "last eight years of Obamanomics has crippled our struggling state," which I suspect is supported more by a political narrative than an analysis of the data.

The new administration is at least fortunate that the problems handed to them are not at the same level as those handed to the previous administration. During the Obama administration, economic growth was admittedly slow, but considering that he took office on the precipice of what could have been the second great depression, these national numbers look pretty good:

- Longest streak in US history of private sector job growth, the difference can be noted by comparing 2008 and 2016 numbers:
  - In November 2008, the economy lost 533,000 jobs.
  - In November 2016, the economy gained 178,000 jobs.
- Unemployment dropped from 10% to 4.6%.
- 800 billion dollar decrease in deficit.
- Deficit as percentage of GDP dropped from 9.8% to 3.2% with no increase in middle class taxes.[fn:2]

To be fair, the economic numbers for the Obama administration are not all rosy, however. A significant worry is the increase in the national debt. Obama's policies added 983 billion dollars to the national debt. The budget deficits under his administration increased the debt by 6.5 trillion.[fn:1]

If the economy of Oklahoma has been crippled, surely the state government, dominated by the right, has played a significant role. 

[fn:1] Determining how much of the national debt a president is responsible for is a tricky matter. One could just look at the total increase in the national debt, but that unfairly saddles a president with a debt increase during the first year that results from the previous president's final-year budget. One could also add up the deficits of the president's budgets, which is fairer than the first method, but saddles the president with deficit spending that was either out of the president's  control or not a result of the administration's policies. The third method, which is the most meaningful but hardest to calculate, is to determine how much the president's policies contributed to the national debt. 
Kimberly Amadeo provides a clear explanation of these methods, along with the resulting numbers, [[https://www.thebalance.com/national-debt-under-obama-3306293][here]].

[fn:2] I originally saw these numbers [[http://www.voices4hillary.com/when-trump-voters-say-they-suffered-for-8-years-under-obama-heres-the--2280512289.html][here]]. Since the article contained no citations of sources, I corroborated and made some adjustments to them using this piece by [[https://www.nytimes.com/2016/12/02/business/economy/jobs-report.html][Patricia Cohen]].


#+begin_tagline
Tagged: politics economics
#+end_tagline
