#+title: My Oklahoma Home
#+date: <2018-10-06>
#+filetags: music


My latest song:\\

VERSE 1: I-40 East, on a cloudy day, Memphis up ahead, had to get away; Had nothing in mind Just looking for a place to roam. Thought I could see, but I was dumb and blind; Gave no thought to what I left behind, The people that I love, and my Oklahoma home.\\

CHORUS: They say that heaven's paved With streets of gold, There’s no more tears Or so I’ve been told No more pain, And no one feels alone. But by those streets Where the children play, I hope to find just a little red clay To remind me Of my Oklahoma home.\\

VERSE 2: Mind starts to wander when you drive for miles, You think about faces, remember the smiles, And you realize you're old, But you've never ever really grown. So you turn the car into the setting sun, The journey goes on, but the running is done. God help me back To my Oklahoma home.\\

VERSE 3: You can’t leave, even if you tried, When you’ve got red dirt deep down inside, No matter how much you wanted To leave it alone. When you’re running away to another town, No road is straight, they all circle around, Bringing you back To your Oklahoma home.\\

BRIDGE: Okemah up ahead, the tears are making me blind, And I hear the voice of Woody deep inside my mind, And It's taken thirty years, but now I understand, That these are my people, and this is my land, And these Oklahoma hills will always be home.


#+begin_tagline
Tagged: music
#+end_tagline
