#+title: Family Separation at the Borders
#+date: <2018-06-19>
#+filetags: politics religion


I tend to find most political issues to be difficult and intricate, requiring complex and nuanced responses. So, I believe that there is generally room for rational disagreement when evaluating particular policy decisions. This, however, is not the case with the current administration's family separation policy — it is simply heinous, cruel, inhumane, and contrary to the teachings of Jesus. We should not return to the Obama administration's lesser evil of locking up children with their mothers. It is past time for Congress to undertake the difficult task of immigration reform. If God is both just and good, then justice and goodness are not incompatible. We could develop an immigration policy that is both just and good, if we were but willing to do the work. I expressed this today to the offices of my congressional representatives. To find yours, go to [whoismyrepresentative.com](https://whoismyrepresentative.com/).



#+begin_tagline
Tagged: [[file:../tags/politics.org][Politics]] [[file:../tags/religion.org][Religion]]
#+end_tagline
