#+title: Prayer in Times of Fear
#+date: <2018-02-19>
#+filetags: prayer religion


God of compassion, In this week of violence and tragedy,\\
we mourn with those who grieve,\\
cry with those who weep,\\
and sit in silence with those in pain. 

But what should never happen even once\\
seems to happen over and over again,\\
until we are left with nothing\\
but bloodshot eyes and numb hearts. 

Even so, Lord, this is our witness: 

You are with us,\\
and in your presence,\\
We will not be afraid. 

We will not fear the world,\\
for it is your creation. 

We will not fear the future,\\
for you have already redeemed it. 

We will not fear the unknown,\\
for surely you have seen it. 

We will not fear the stranger,\\
for that person was made in your image,\\
even as we are made. 

We will not fear our weakness,\\
for you will give us strength. 

We will not fear the darkness,\\
For we carry the light with us. 

You are there,\\
and we are not alone. 

We will not be afraid. 

/Amen/



#+begin_tagline
Tagged: [[file:../tags/prayer.org][Prayer]] [[file:../tags/religion.org][Religion]]
#+end_tagline
