#+title: Homily for Maundy Thursday
#+date: <2018-03-30>
#+filetags: sermons


With the end of every semester comes the last day of class. It's the perfect opportunity to sum up everything that is important about the subject, and leave students with a final word, something so profound that they will remember it the rest of their lives. In over 20 years of teaching philosophy at the university level, I've never been able to do it. One of two things tend to happen. Generally, I'm so far behind that I spend the last class period cramming material in that they need to know for the final exam. At the end of an hour, which I spent talking as fast as I could, and they spent writing as fast as they could, I say something like, "We're out of time. Good luck on the final, and may God have mercy on your souls." At other times, I'm just worn out at the end of the semester, and halfway through the last class, just say, "I guess that's enough." To borrow a phrase from T.S. Elliot, this is way the class ends, not with a profundity, but with a whimper. Over the past few days, I've had the opportunity to think about the context of John chapter 13. My father will be admitted to hospice care tomorrow. He is expected to live for, at most, another week. He is now non-responsive — he cannot speak, and we do not know if he can understand anything we say. So, I am confronted with the realization that, for all I know, my dad and I have already had our last conversation. There is always one chance that is the last chance, but we hardly ever know that it was indeed the last chance. We want our final words to be meaningful, but, because of the ignorance of our human condition, they rarely are. Fortunately, Jesus had an insight that I lacked. Chapters 13 through 17 of the Gospel of John are called the "Farewell Discourse," and record his final words to his disciples before the events of Good Friday. John tells us that Jesus got up from the table, took off his robe, and tied a towel around himself. He poured water into a washbasin, then knelt and began to wash the feet of his disciples. When he had finished, he said this to them, "Do you know what I have done to you? You call me Teacher and Lord — and you are right, for that is what I am. So if I, your Lord and Teacher, have washed your feet, you also ought to wash one another's feet. For I have set you an example, that you also should do as I have done to you." Then, after he foretold his upcoming betrayal, he got to the heart of the matter. John 13:33–35 records what I believe to be some of the most important words in the Bible:

#+begin_quote
Little children, I am with you only a little longer. You will look for me; and as I said to the Jews so now I say to you, "Where I am going, you cannot come." I give you a new commandment, that you love one another. Just as I have loved you, you also should love one another. By this everyone will know that you are my disciples, if you have love for one another.
#+end_quote

From this phrase, 'A new commandment,' or in Latin, /mandatum novum/, we get the name for this day in the church calendar, Maundy Thursday. I can picture the disciples nodding their heads in assent as Jesus said these words, for a commandment to love was nothing new. It was already something that every Jew meditated on, and knew by heart: "Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind" and "Thou shalt love thy neighbor as thyself." Jesus though, did not command his disciples to love their neighbors as themselves; instead, he commanded them to love each other as /he/ loves them. This might have looked easy on Thursday, but it became practically impossible once the events of Friday unfolded. If we are so commanded, it must be possible to fulfill that command. How, though, can we ever hope to love like Jesus? If we only open our eyes to see, Jesus himself shows us what must be done. When a Jew dies, a small group of people who are known as /chevra kadisha/ prepare the body for the upcoming burial. The body is first, very reverently undressed, and any wounds on the body are carefull cleansed. Any rings, bracelets, and jewelry are removed. The body is then bathed and purified with water, then wrapped in a white sheet and maybe a prayer cloth. The sheet is tied with a sash that is fastened with a sacred symbol. Only then, is this body ready to meet the living God. When I think of this ritual, I think of Jesus who laid aside his robe and tied a towel around his waist. Today, he is stripped to serve, but tomorrow, he will be stripped to die. Dietrich Bonhoeffer, facing his own impending death, wrote this in his letters from prison: "I think that even in this place we ought to live as if we had no wishes and no future, and just be our true selves." That is the key, we must strip away all of our pretensions and our pride. We must even, for a moment, forget that there will be a future, and be only who we truly are at this single moment in our lives, with all of our failures, pain, and loss. It is then, and only then, that we can truly love and be truly loved. If we were to live like this, we would find that we never miss a chance for those final words, for we will have been saying them our entire lives. 

/Amen/



#+begin_tagline
Tagged: sermons
#+end_tagline
