#+title: Homily for Ash Wednesday
#+date: <2018-02-15>
#+filetags: religion


/Delivered on February 14, 2018 at NorthHaven Church, Norman, Oklahoma./ 

Like most people, I have a somewhat love-hate relationship with myself, which means that I also have a love-hate relationship with mirrors. When I pass by a mirror, I can never resist the urge to look, but I'm never completely satisfied with what I see. I look into some mirrors, and I'm confronted with the cold, harsh reality — the ugly truth, as it were. I look into other mirrors, like those found at the carnival, and I like what I see; I'm a bit taller, and a bit thinner. Neither mirror can give me what I need. The first mirror shows me the truth, but only as it is now, whether I want to see it or not. The second mirror shows me what I want to see, even if it could never be possible. What I need is a mirror that shows me what I truly am, but also gives me a glimpse of what I truly could be. That's the mirror I need, even if it may not be the mirror I want. We have such a mirror in Scripture. In fairness, we must confess that we can bend and distort Scripture so much that it functions exactly like those carnival mirrors, showing exactly what we want to see, confirming our desires and reinforcing our biases. There are times, though, when I come to the text openly and honestly, and it shows me who I am, as I cry with David in Psalm 51:

#+begin_quote
For I know my transgressions, and my sin is ever before me. Against you, you alone, have I sinned, and done what is evil in your sight, so that you are justified in your sentence and blameless when you pass judgment. Indeed, I was born guilty, a sinner when my mother conceived me.
#+end_quote

But Scripture can also show me what is genuinely possible — the beauty of a life lived fully in the Kingdom of God; more than just a glimpse of who I am, but a vision of who God wants me to be. The book of Isaiah was written when the people of Judah desperately needed both of these mirrors. The small nation of Judah, what was left of the once mighty nation of Israel, had not only been defeated by Babylon, but had been taken away in captivity. The people of God were apparently forsaken by their God — prompting the psalmist to lament, "By the rivers of Babylon—there we sat down and there we wept when we remembered Zion." Even in the midst of that despair, however, there is a voice of hope. We hear it in what are called the "servant songs" of Isaiah, found sprinkled in the text, from chapter 42 through chapter 53. In these passages, God speaks of his promised servant, who will establish justice in chapter 42, be the light to the nations in chapter 49, be vindicated in the face of humiliation in chapter 50, and exalted and lifted up in chapter 52. And so, we sit back and wait for the promised servant, the one who will finally do the will of God. Who is this servant? It is difficult to read chapter 53 and not see Jesus there in the text:

#+begin_quote
But he was wounded for our transgressions,\\
crushed for our iniquities;\\
upon him was the punishment that made us whole,\\
and by his bruises we are healed.
#+end_quote

I do believe that this text speaks prophetically of the Crucified Christ, but that doesn't mean that the servant songs are simply about Jesus, a point that is made clearly in Isaiah 41:8,

#+begin_quote
But you, Israel, my servant,\\
Jacob, whom I have chosen,\\
the offspring of Abraham, my friend;\\
you whom I took from the ends of the earth,\\
and called from its farthest corners,\\
saying to you, 'You are my servant, ....'
#+end_quote

A message that is repeated in chapters 44, 45, and 49: /We will see the servant, if we will but look in the mirror/. The reflection that we see, however, is harsh and unyielding. It is a clear picture of what God wants us to be: people who seek justice, something that is mentioned three times in the first four verses, yet seek it in a way that is not self-serving. It is a kind of justice that does no harm to the weakest in society — we are to be the light to the nations, helping the blind to see, and freeing those who are in darkness and imprisoned, in a way that does not call attention to ourselves. It is, at the same time, a beautiful image of what can be, and a devastating contrast to what now is, one that forces me to ask, what is it that I really seek? 

/Is it justice, or merely my own advantage?/ 

/Is it righteousness, or merely my own rights?/ 

/Is it to serve, or to be the one who is served?/ 

This day, Ash Wednesday, is the day on which the church is faced with the truth. The ashes are remnants of the palms that we waved on Palm Sunday, a vivid reminder of how quickly our vows of dedication to God become cries of denial and betrayal. We come before the altar of God to hear the humbling words, "Remember, you are but dust, and to dust you shall return." We come, bringing our pride, our pretension, our vanity, and our feelings of superiority to be cleansed in God's holy fire. Out of the ashes that are left, God has chosen to raise up his servant. Thanks be to God, for his mercy and grace. 

/Amen/

