#+title: Some Thoughts on Mass Shootings
date: <2019-08-06>

** The Second Amendment

Despite the Supreme Court’s 2008 Heller [[https://www.oyez.org/cases/2007/07-290][decision]], I have never thought that a reasonable reading of the 2nd Amendment guaranteed an individual’s unequivocal right to possess firearms. In fact, the only Supreme Court decision that focused on the 2nd Amendment, [[https://www.oyez.org/cases/1900-1940/307us174][US vs. Miller]] in 1939, found that there is no individual right to bear arms independent of the nation’s self-defense interests. There is also reason to believe that Madison wrote the 2nd Amendment to protect the rights of southern states to have militias that they could use to put down slave revolts.[fn:1]

I do believe, however, that every person has an inherent right to self-defense.[fn:2]  I take this to not be a civil right enshrined in law, but as a basic human right. Although there are weapons that are designed to be used for defensive roles, assault rifles, by definition, are not. I have no sympathy for those who argue that their guns are necessary for defense against a tyrannical government. I have seen four [[https://www.youtube.com/watch?v=bGrNkl8HzPw&app=desktop][Apache helicopters]] on an attack run at a range in Fort Hood. If you think that your AR-15 will defend you, you’ve been watching too many bad action movies.[fn:3]

** Good Guys with Guns

Lately, there have been demands to arm teachers to prevent school shootings. This is a variation on the idea that the only solution to gun violence is more good guys with guns. There are obvious reasons why this is untenable. We had problems with active shooters when I was in Afghanistan. The solution was not to have more people carrying guns, since everyone except me and the other two chaplains were already armed. The solution was to have a soldier standing at the ready at every meeting, doing nothing but looking for signs of hostility, prepared to shoot as soon as a weapon was drawn. That's what the only "more guns" solution looks like – an armed guard standing with weapon drawn in every classroom, in every corridor of the mall, covering every line of sight in every public venue, etc.[fn:4]  That's not a country where I want to live.

Possible Solutions
------------------

Mass shootings are a complex problem, but not irreducibly complex. We shouldn’t pretend that our only options are an impossible perfect solution and doing nothing. So, what should be done? There are some means that, I believe, would help reduce the level of gun violence.

1.  Treating sources of terrorism consistently would be a good first step. White nationalism has always been an ideology associated with terrorism, from the lynchings of Reconstruction to the mass shooting in El Paso. As a terrorist ideology, white nationalist demands for racial purity are no different than demands for religious purity from other movements that we rightly label as terrorists.
2. Ban assault weapons --- that has already been shown to be effective.
3.  Ban high capacity magazines. Otherwise, thirty people are dead before the “good guy with a gun” has an opportunity to respond.  

May God forgive me, if I ever demand my rights at the possible expense of another human being’s life.

* Footnotes

[fn:4] That doesn’t mean that a member of the public with a gun will not occasionally act to prevent, or minimize, some tragedy. That will have to be weighed against members of the public misidentifying a target or harm done by negligent discharges, a particular problem that we had in Iraq.

[fn:3] I’ve also recently heard that when criminals get semi-automatic weapons, then citizens need full-auto. In my infantry days, the only situation in which fully automatic fire was used was to spray a room with bullets before entering. So, saying this is the same as saying “When criminals get semi-auto, then citizens kill indiscriminately.”

[fn:2] Specifying this right will, by no means, be simple. I do not believe that people have the right to do /anything/ that will result in saving their lives. I also do not believe that the right to self-defense is automatically a right to kill, if there are other effective means available. There are also tricky questions about prisoners on death row, etc. This is also a right that implies certain duties, like the duty to ensure, as much as possible, that no innocent people are harmed. This means that gun-owners have a duty to acquire and maintain a high level of skill. This could mean that the public has a right to demand that those who wish to carry firearms in public be tested and certified. 

[fn:1] Conservatives had no problem with gun control when the Black Panthers were taking up arms to press for equal civil rights. As Governor of California, Ronald Reagan signed an act in 1967 banning the carrying by members of the public of loaded firearms in cities. He [[https://books.google.com/books?id=5PRABAAAQBAJ&pg=PT73&lpg=PT73&dq=%E2%80%9Cwould+work+no+hardship+on+the+honest+citizen.%E2%80%9D+reagan&source=bl&ots=cq6Kl3wRXB&sig=AaCua1410lGebtc18y0CD85uRok&hl=en&sa=X&ved=0ahUKEwjvivOHxNfWAhUn4IMKHYaDAuYQ6AEINzAD#v=onepage&q=%E2%80%9Cwould%20work%20no%20hardship%20on%20the%20honest%20citizen.%E2%80%9D%20reagan&f=false][said]] there is “no reason why on the street today a citizen should be carrying loaded weapons.” It's also curious how reticent the NRA is to come to the defense of registered African-American gun owners.
