#+title: Cancer
#+date: <2019-06-05>
#+filetags: cancer


In March, I started to notice blood in my urine. At Sheri's insistence, I made an appointment to see our family doctor. After waiting two weeks for approval from the insurance company, I was referred to a urologist, Dr. Archer in Oklahoma City. After another two weeks of waiting for approval, the urologist performed a procedure to see if anything was wrong with the bladder. He noticed tumors, and diagnosed it as an invasive bladder cancer.

He then referred me to Dr. Stratton at the Stephenson Cancer Center at OU. Dr. Stratton scheduled the same procedure, since Dr. Archer was not able to go very deep. He told us that the treatment options were dependent on the depth of the tumor. If the tumor extended into the muscle, then the only option is to remove the bladder. If not, then the cancer is treated with BCG, the vaccine for tuberculosis.

The results were good – I do not now need to have the bladder removed, and I have been admitted to a clinical trial of BCG. My first treatment is on Thursday, June 6.



#+begin_tagline
Tagged: [[file:../tags/misc.org][Misc]]
#+end_tagline
