#+title: Thoughts on The Fine-Tuning Argument
#+date: <2019-02-14>

Yesterday, Paul Gould from Southwestern Baptist Theological Seminary presented a very interesting talk titled, “Cultural Apologetics: Renewing the Christian Voice, Conscience, and Imagination in a Disenchanted World.” In it, he argued for two important claims:

1.  The world is fine-tuned for human life, and
2.  The world is fine-tuned for human flourishing.

The argument from fine-tuning is particularly fascinating in that, as Paul rightly pointed out, everyone agrees on the data, just not on what the data shows. As I continued to think about the presentation while driving home, I realized that I can’t even agree with myself on what the data shows.

** The Argument


The physics may be complicated, but the idea behind the argument is simple. Take a factor like the initial strength of the explosion at the Big Bang. Had the strength of that explosion differed by as little as one part in 1,060, the universe would have either collapsed back on itself, because the explosion was not strong enough to overcome the strength of gravity, or it would have expanded too fast for stars to form. So, had the force of that explosion been even slightly different, life would never have had a chance to form.

That factor is just one of many. By some estimates there are over 100 factors, and had any one of them been just slightly different, life would have been impossible. It is difficult to conceptualize the degree of tolerance here. An accuracy of 1 in 1,060 has been compared to firing a bullet and hitting a one-inch target twenty billion light years away on the other side of the observable universe. That’s just for one factor, the probability of all of the factors having the precise values that they do must be incredibly low.

So far, that’s nothing controversial. The universe appears to be fine-tuned for life. The controversial move is the inference from apparent fine-tuning to the probability of a fine-tuner. The intuition is that, considering the very many different ways the universe could have been, it is /very unlikely/ that we would have ended up with this world if there were no creator. On the other hand, if there were a creator, it is /very likely/ that a world capable of sustaining life would be created. Now, it becomes a Bayesian problem. Let /L/ be a life sustaining universe and /D/ be the existence of a designer, the probability of a designer given that the universe sustains life is

\( \Pr(D \vert L) = \frac{\Pr(D) \times \Pr(L \vert D)}{\Pr (L)} \)

The probability that there is not a designer, given a life sustaining universe is

\( \Pr(\neg D \vert L) = \frac{\Pr(\neg D) \times \Pr(L \vert \neg D)}{\Pr (L)} \)

Since the denominators are the same, \( \Pr(D\vert L) > \Pr(\neg D \vert L)\\) if and only \\( \Pr(D) \times \Pr(L \vert D) >\Pr(\neg D) \times \Pr(L \vert \neg D)\). Now, all we need to know is the prior probability of God existing, and we would know the probability of a life-sustaining universe on the assumption that there is a God. Easier said than done, as they say.

Instead, maybe we should rethink the strategy. If I knew how each additional factor affected the probability, then I might be able to assess how low the prior probability of /D/ must be in order for the evidence to /not/ raise \( \Pr(D\vert L)\) over 0.5. To do this, we can use the odds version of Bayes' theorem: the odds of /D/ given /L/ is equal to the prior odds of /D/ times the likelihood ratio:

\( O(D \vert L) = O(D) \times \frac{\Pr (L \vert D)}{\Pr (L \vert \neg D}\)

Now, let's take that \( \frac{1}{1,060}\) tolerance from above, but let's change it to  \(\frac{1}{1,001}\). This does two things. First, it favors atheism some, but, more importantly for me, it makes the math much easier, because it makes the likelihood ratio a nice round number:

\( \frac{\Pr (L \vert D)}{\Pr (L \vert \neg D} = \frac{\frac{1,000}{1,001}}{\frac{1}{1,001}} = \frac{1,000}{1}\)

That means that with each new factor, the odds of the the universe being intentionally fine-tuned increase by a factor of 1,000. With 100 factors, the odds of theism are equal to the prior odds times \(1 \times 10^{300}\). This means that, in order for it to be less likely that God exists, given apparent fine-tuning, the prior odds of God existing must be less than \(\frac{1}{10^{300}}\)

Now, I admit that I don't know if all the factors have the same odds. I just know that some of them have been estimated to be higher than the value that I used. So, let's just lower the odds by a power of 100. That is, now the degree of tolerance for each factor is a mere 1 in 10. If so, then the prior odds of God existing would still have to be lower than 1 in 1,000 before it would be unlikely that theism were true.

At some point, I'll consider some objections and responses.

