#+TITLE: Frankl on Self-Actualization
#+date: <2025-11-14 Fri 14:45>
#+filetags: 
#+setupfile: ../org-templates/post.org

#+begin_quote
By declaring that man is responsible and must actualize the potential meaning of his life, I wish to stress that the true meaning of life is to be discovered in the world rather than within man or his own psyche, as though it were a closed system. I have termed this constitutive characteristic "the self-transcendence of human existence." It denotes the fact that being human always points, and is directed, to something, or someone, other than oneself—be it a meaning to fulfill or another human being to encounter. The more one forgets himself—by giving himself to a cause to serve or another person to love—the more human he is and the more he actualizes himself. What is called self-actualization is not an attainable aim at all, for the simple reason that the more one would strive for it, the more he would miss it. In other words, self-actualization is possible only as a side-effect of self-transcendence.
#+end_quote

#+ATTR_HTML: :class source
Frankl, Viktor E., /Man's Search for Meaning/

#+begin_tagline
Tagged: 
#+end_tagline
